### ISSUE TITLE
Stuck on rowy-run 1.0.0

### ISSUE THREAD

**Issue by gregdingle** [rowyio/rowy#1063]
I'm always getting 1.0.0 reported even after I delete the services and reinstall.

<img width="592" alt="CleanShot 2023-01-07 at 00 14 10@2x" src="https://user-images.githubusercontent.com/28797/211132454-052e5fa5-5a56-453b-b858-9d728d9b9468.png">

**Comment by harinij** [comment]
Hi @gregdingle thanks for highlighting that. We have now resolved this issue and your RowyRun should be up to date. Let us know if you still facing any issues with this.
