### ISSUE TITLE
Derivatives failing with "Cannot read properties of undefined (reading 'path')"

### ISSUE THREAD

**Issue by gregdingle** [rowyio/rowy#1064]
**update**: Seems like a dupe of https://github.com/rowyio/rowy/discussions/1053

**To Reproduce**
1. Go to a table that has a derivative col
2. Click on "evaluate all"
3. See error

**Screenshots**
<img width="438" alt="CleanShot 2023-01-07 at 00 19 15@2x" src="https://user-images.githubusercontent.com/28797/211132526-31880907-2244-4477-8dbd-47f40e9b2b15.png">

**Rowy Run version**
latest version, reinstall today

**Additional context**
I never got it derived to work correctly so I don't know what success looks like.

And here is my settings.

<img width="484" alt="CleanShot 2023-01-07 at 00 21 44@2x" src="https://user-images.githubusercontent.com/28797/211132553-333d3f9b-f858-4f65-aa57-19d4fb3ac1e3.png">

And code.

<img width="618" alt="CleanShot 2023-01-07 at 00 27 12@2x" src="https://user-images.githubusercontent.com/28797/211132764-12e888b2-a3e8-4380-82e1-69c35a515cc7.png">

**Comment by gregdingle** [comment]
Seems like a dupe of https://github.com/rowyio/rowy/discussions/1053

**Comment by shamsmosowi** [comment]
should be fixed now

**Comment by gregdingle** [comment]
When is the fix being released? I don't see it.
