### ISSUE TITLE
Basic Webhook: custom response body

### ISSUE THREAD

**Issue by deondejongh** [rowyio/rowy#1069]
### Discussed in https://github.com/rowyio/rowy/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **deondejongh** January  8, 2023</sup>
Hi all!

I was tinkering a bit with the webhooks function (specifically the Basic Webhook) and wondered how I would customise the response for a received request. 

Specifically, I'm looking to use the YouTube Data API's notification system (pubsubhubbub, found [here](https://pubsubhubbub.appspot.com/subscribe)) to listen for new videos uploaded to a channel and then populate a row with the video's information (parsed from the XML data received via the POST request). 

However, when I'm trying to set it up, the problem I'm running into is that the above-mentioned YouTube notification system requires that the webhook responds in its 'OK' / '200' status's body with a specific string - as contained within this initial set-up GET request's queries ("hub_challenge").

How can I include that "hub_challenge" string received via YouTube's GET request within's Rowy's 'OK' / '200' response body?

Any advice would be greatly appreciated - thanks in advance!</div>

**Comment by bofeiw** [comment]
Hi, there is a hack to send custom information through webhooks response. We are making changes to improve this. 

The hack is that you can send anything through the `res.send` function.
```js
res.send({
  hub_challenge: "some text",
})
```

Hope this will work for you.

**Comment by deondejongh** [comment]
Thanks @bofeiw !

I actually did try to use that in the 'Conditions' section on the webhook's settings on Rowy.io - did not work, and thus created this issue.

However, when I had a closer look at the `rowy_hook` source code, I saw that `res.send` is actually not available in "Conditions" but actually in the "Parser" settings:
![image](https://user-images.githubusercontent.com/65919982/211244398-8d72bed7-1f62-49e0-9112-1f489ccbc040.png)

Tried that, and it worked ... for subscribing to the YouTube feed and sending back the `hub.challenge` query data, but the next issue I ran into was that the YouTube feed data being received by the webhook is XML data - and from what I can see, I first need to translate it to JSON for `rowy_hook` to then be able to parse it for writing it to the Firestore database.

I don't see a way, on Rowy.io (specifically the webhook settings with "Conditions" and "Parser"), to either convert the XML to JSON or even just dump the entire XML into a field (i.e. to skip trying to parse the data into key-value pairs) - or is there perhaps a hack for that as well?

Instead, I forked `rowy_hooks`, linked the forked repository to Google Cloud Run's continuous deployment, and will try and attempt to add the functionality in the source code (bold statement for someone like me who has pretty much never coded).

**Comment by bofeiw** [comment]
To save XML values received from webhooks in Rowy table, you can return the XML value in an object in the parser so it will be added as a new row:
`return {xml:body}`

Then you can use a Derivative column to translate xml into field values. You can take advantage of any npm packages.

**Comment by deondejongh** [comment]
Thanks for your assistance @bofeiw - very much appreciated!

I tried your above suggestion, with my Parser code on Rowy.io looking as follows:

```
const basicParser: Parser = async({req, res, db, ref, logging}) => {
    const challenge = req.query["hub.challenge"];
    if (challenge) {
    res.send(challenge);
    return;
        }
     const {body } = req;
      return {xml: body};
  }
```
I then tested it both with JSON and XML POST requests. 

- JSON :

    - Request:
![image](https://user-images.githubusercontent.com/65919982/211385825-d232de53-f5fa-490d-8f57-e6e4716eb45c.png)

    - Firestore record:
![image](https://user-images.githubusercontent.com/65919982/211385997-d2a7175d-c689-42f4-865b-9e6d0ad3e42f.png)


    - The JSON seemed to kind have worked, but it still seems to have parsed the body into key-value pairs underneath a map ("xml"). I think I half-expected it to have one key ("xml") with the entire raw body of the request being the value. (Hope I'm making sense.)

- XML:

    - Request:    
![image](https://user-images.githubusercontent.com/65919982/211387674-ee3b72eb-1371-42c0-bd8b-923e91d8a91a.png)

    - Firestore record:
![image](https://user-images.githubusercontent.com/65919982/211387827-fa84d771-8c40-4a95-8a75-a9b53b4456f4.png)

    - Here we see that the "xml" map is again created, but it's just empty / no key-value pairs even.

If you're able to provide any assistance, I'll be very grateful - please and thank you in advance! (I'm pretty sure there's a very elegant and simple solution - I'm just not well-versed, or at all really, in JavaScript ... to whatever it is that we're working with here)

**Comment by bofeiw** [comment]
Upon a closer look at the source code, it seems like with the current implementation of Rowy Hooks, it is not possible for it to accept raw data in XML format. 

Rowy Hooks only accepts JSON data as it is [implemented with the built-in Express middleware](https://github.com/rowyio/rowy-hooks/blob/master/src/index.ts#L38). To add XML support, we have to modify source code. Please feel free to open a pull request if you have a solution, it will be helpful to others as well. 

Adding XML support is important but it will take some time. Alternatively, you can check if JSON format is available as it is the easiest solution.
