### ISSUE TITLE
Unique Rowy URLs per filter combination

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1071]
### Discussed in https://github.com/rowyio/rowy/discussions/1065

<div type='discussions-op-text'>

<sup>Originally posted by **gregdingle** January  8, 2023</sup>
It would be very useful to get a URL that represents the current filtered view of a table.
1) share with colleagues
2) bookmark for self
3) link to from other tables as a way of show foreign key data (id in one table cell links to filtered view in another table)

For example:

https://rowy.app/p/test/table/documents#filters:documentData.copy_count>0

<img width="890" alt="CleanShot 2023-01-07 at 08 15 00@2x" src="https://user-images.githubusercontent.com/28797/211152637-69fe14ea-c95e-4dd7-af61-c112bbd6890d.png">
</div>

**Comment by staticGuru** [comment]
@harinij , I am working on the changes

**Comment by harinij** [comment]
Hi @staticGuru Great thanks, I have assigned it to you. Join our Discord community and feel free to chat on the #contribution channel in case you need any info.

**Comment by staticGuru** [comment]
Hi @harinij 
I hope you doing well.
I worked on the features and created PR #1256 .
Kindly check
