### ISSUE TITLE
When column type is "Status" and the row value is 0, the "label" is not displayed.

### ISSUE THREAD

**Issue by victorFSL** [rowyio/rowy#1091]
**Describe the bug**
When the column type is "Status" and the row value is 0, the "label" is not displayed but instead shows a 0.

![image](https://user-images.githubusercontent.com/21147102/214203981-e0e6428e-bc73-4dbe-a51f-e7d94277714d.png)
This is how I set it up.

![image](https://user-images.githubusercontent.com/21147102/214204034-bd8a69a8-ceeb-4ec6-b9c1-b0b841533dc9.png)
This is how it looks.

For some reason when I try to choose "Draft" in this scenario, nothing happens.

**To Reproduce**
1. Create a status column.
2. Assign a condition of equal to 0.
3. Try to assign that label.

**Expected behavior**
I expected the label to be displayed as "Draft" instead of 0.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser Chrome Version 109.0.5414.74

**Comment by victorFSL** [comment]
Also, I cannot set a "default" value of "Draft", the drop-down comes back empty. I am pretty sure they are related.

**Comment by Nike682631** [comment]
Can I work on this?

**Comment by harinij** [comment]
Hi @Nike682631 👋 thanks for taking a look. I have assigned this to you now 👍

**Comment by harinij** [comment]
Hi @Nike682631 checking to see if you need any additional inputs or if you are still working on this issue?

**Comment by Nike682631** [comment]
Un Assigning myself for now. Too much stuff to deal with these days. Will be back incase noone else picks this up or will contribute to other issues around.

**Comment by harinij** [comment]
Hi @alceil, sure have assigned it to you now.

**Comment by mnmt7** [comment]
@alceil, are you still working on this issue? If not, @harinij, can I have the issue assigned to me?

**Comment by harinij** [comment]
Hi @alceil checking if you are still working on this? If not I can reassign to @mnmt7.

**Comment by alceil** [comment]
Yes im am @harinij will raise a pr soon.

**Comment by alceil** [comment]
Hey, I have raised a pull request. Can you please have a look? @harinij

**Comment by harinij** [comment]
Thanks @alceil for the contribution 🎉 It's merged and closing this issue now.
