### ISSUE TITLE
Unexpected crash while resizing columns

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1111]
Originally posted by @DayneLinx in discussion #1034.

**Describe the bug**
I expanded a column using the handle to make the column wider and the instance crashed.

**To Reproduce**
1. Go to a Rowy project table.
2. Try to resize the column using the handle.
3. See error:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/53828745/216910843-9fb47343-0275-422c-b065-ea8d4012828b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Browser Chrome 109.0.0.0

**Comment by HeikoKanzler** [comment]
Same here. Mac Safari or Chrome, doesn't matter.

**Comment by harinij** [comment]
This bug has been fixed in our recent releases @HeikoKanzler @webwurm and you shouldn't be experiencing this anymore. Please let us know if you do.
