### ISSUE TITLE
Derivative-fields not executing; Axios-Error in logs

### ISSUE THREAD

**Issue by webwurm** [rowyio/rowy#1120]
**Describe the bug**
Derivative-fields that catch data from another collection don't work and are not triggered

**To Reproduce**
1. Create 3 collections, one "Users", one "SearchProfile" and one "Objects", fill with data. The SearchProfile-collection has a referrer-field to the Users-collection called "refUser".

2. Create a derivative field in the Objects-collection that picks up data from the SearchProfiles-collection, like so, when triggered by the field "refSearchProfile":
```
  const searchProfileDoc = await row.refSearchProfile.get();
  return searchProfileDoc.get('refUser');
```

3. Sometimes this function is not triggered, but should be. Weirdly sometimes not for hours, then it works again; 

In the Cloud-Logs of Google you can see this error many times:
```
AxiosError: timeout of 1000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/layers/google.nodejs.yarn/yarn_modules/node_modules/axios/dist/node/axios.cjs:2998:16)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:552:15)
    at Timeout.<anonymous> (/layers/google.nodejs.yarn/yarn_modules/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
```

**Expected behavior**
The fields should be always triggered, not just sometimes

**Rowy Run version**
I'm working on rowy.app

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 110.0.1587.41

**Additional context**
This keeps happening in different collections of my project. Again: Sometimes it works, then for hours it doesn't; then it seems to work again. I already wrote about this [here](https://github.com/rowyio/rowy/discussions/1092)

**Comment by bofeiw** [comment]
Fixed in https://github.com/rowyio/backend/pull/27
