### ISSUE TITLE
rowy.app sends thousands of request per minute to the google firestore API 

### ISSUE THREAD

**Issue by pcaneill** [rowyio/rowy#1137]
**Describe the bug**

rowy.app sends thousands of request to the google firestore API consuming all the READ credits.

**To Reproduce**
1. Go to a Table
2. Open up the Developer Network Tab
3. See all the requests that are made

**Expected behavior**

I would expect rowy not to do thousands of API call per minutes

**Screenshots**

![image](https://user-images.githubusercontent.com/1199435/221403988-7a750aff-65d4-4973-9835-e481f4696620.png)

![image](https://user-images.githubusercontent.com/1199435/221404024-64ffef0e-2697-4d77-ad35-51c9ccfcf116.png)

**Rowy Run version**

N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser brave, chrome

**Comment by harinij** [comment]
Hi @pcaneill there was a bug introduced in the latest release with table sort which we have now fixed and released [here](https://github.com/rowyio/rowy/pull/1139).
