### ISSUE TITLE
Full Text Search: Incompatible Firestore field types with Meilisearch

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1177]
Originally posted by: Jim#5216 on Discord Support Forum

**Describe the bug**
I'm trying to use ROWY as content management for a FF project. I need to create, edit, delete records which include Lat Long (Geopoint). I need to be able to search ~3000 rows to find the document I want to edit.
But, when I search the Lat Long column changes. Suddenly all values change to "invalid value". The correct Lat Long comes back when I remove the search text.

**Additional context**
The Full-Text Search is a relatively new feature, and we see that some Firestore data types are currently incompatible with MeiliSearch. It is probably because of this, that the Geopoint field displays 'Invalid Value'.

**Comment by iamanishroy** [comment]
Fix: https://github.com/rowyio/rowyapp/pull/113
