### ISSUE TITLE
Rowy Backend has a completely unacceptable telemetry system

### ISSUE THREAD

**Issue by Shakahs** [rowyio/rowy#1178]
I am using Rowy in a self-hosted environment.

1. Rowy Backend authentication middleware [sends telemetry and personal user information](https://github.com/rowyio/backend/blob/848ca7a06316962785c6ace5de3bf44c3653add5/src/middleware/auth.ts#L11) to Rowy for every API call **before** fulfilling the request. 
2. This telemetry request is _blocking_, meaning that if your telemetry system is down or my Rowy Backend is behind a firewall with no internet access, **every single backend request fails, just because the _telemetry endpoint_ isn't available**.
3. Even when telemetry is reachable, this increases the latency of every request.
4. Not only is this incredibly poor design from a devops standpoint, but the telemetry request includes the name and email of the user, making this a privacy violation.  There is absolutely no disclosure anywhere in this open source project that self hosting Rowy will send you my private information, there is no privacy policy, and there is no way to turn this telemetry off. 

As a California resident, these actions violate my privacy rights under the CCPA law.

**Comment by harinij** [comment]
Hi @Shakahs - Thanks for pointing that, we have removed the user token from telemetry and it is now merged as per this [PR](https://github.com/rowyio/backend/pull/33).

To clarify the open-source Rowy app's frontend does not use any telemetry. If you choose to use the backend code functionality which is offered under Apache2.0 license as-is, then it has telemetry which we have also added as a note more explicitly in the manual install section of the backend [documentation](https://docs.rowy.io/rowy-run#manual-install-rowy-run) now.
