### ISSUE TITLE
Safari Compatibility: Safari Number picker takes over and doesn't allow decimals.

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1181]
Originally posted by: HeikoK#9683 on Discord Support Forum

**Describe the bug**
 As soon as add data (currency) via my App, the data is correctly stored in Firebase and displayed in Rowy, but as soon as I click in the field, the values are set to zero. I figured out that this is a problem with Safari. Set aside that the table view is pushing the content out of the cell, the Safari Number picker takes over and only allows integers. Check also the editor to the right. Once you press either . or , the value is set to zero. I attached a small video showing this (The values are updated in Firebase and this is reflected in my mobile app).

**Screenshots**

https://user-images.githubusercontent.com/53828745/228250381-c5c01fff-d609-470f-a065-2ba66437c431.mp4

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Browser: Safari
 - Version: 16.3

**Comment by zcesur** [comment]
hi @bofeiw, this is zaf from algora

for your command to go through, you need to sign up with your rowy.io email address (to join the [rowy org on algora](https://console.algora.io/org/rowyio)) & link your github account. sorry for the inconvenience!

**Comment by bofeiw** [comment]
Thank @rjackson for fixing the issue and providing detailed explanation. Good job!
