### ISSUE TITLE
Support projects with app-check enabled

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1192]
Requested by: VB#6131
**Is your feature request related to a problem? Please describe.**
By presenting users with a reCAPTCHA challenge during the login process, the website or application can verify that the user is a human and not a bot. This helps ensure that only authorized users can access the system, and reduces the risk of security breaches or fraud.

**Additional context**
For reference: https://firebase.google.com/docs/app-check/web/recaptcha-provider#web-version-9

**Comment by khaitanvaibhav** [comment]
Firebase allows app based restriction to data called AppCheck. It checks for Recaptcha and only then allows.

My db is protected by Appcheck. So Rowy will not work at all without Recaptcha integration.

**Comment by khaitanvaibhav** [comment]
Any update?

**Comment by BeeBombshell** [comment]
Hey @khaitanvaibhav, we've added the support for AppCheck on Rowy! 🚀 Here's the link to the documentation for you to enable AppCheck for your project: https://docs.rowy.io/how-to/app-check.

**Comment by khaitanvaibhav** [comment]
You guys (ladies included) are awesome!
