### ISSUE TITLE
Special Characters (encoding utf-8)

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1202]
### Discussed in https://github.com/rowyio/rowy/discussions/1197

<div type='discussions-op-text'>

<sup>Originally posted by **omarammura-dev** April  2, 2023</sup>
Hello , 
i have a CSV file full of data, some of this data contain German alphabet like (Ö, Ü, etc...). the CSV file shows all characters just file but when i import the table it's shows (? or some other symbol) so do you have any encoding extension in your website ?</div>

**Comment by USKhokhar** [comment]
When you import a CSV file containing non-ASCII characters like German umlauts (Ö, Ü, etc.), it's important to make sure that you're using the correct encoding for the file. CSV files are usually encoded in UTF-8, which supports all Unicode characters including German umlauts.

If you're using a programming language to import the CSV file, you can specify the encoding type in your code. For example, in Python, you can use the encoding parameter when opening the file:

python

```
import csv

with open('my_file.csv', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        print(row)
```

If you're using a spreadsheet program like Microsoft Excel to import the CSV file, make sure to select the correct encoding type when opening the file. In Excel, you can choose the encoding type in the "File Origin" dropdown menu in the Text Import Wizard.

**Comment by bhaveek424** [comment]
Hi @harinij I tried recreating the issue by importing a csv file with german characters in it, but they look fine when imported. Is the issue solved?
