### ISSUE TITLE
Bug: Formula field value does not show up on the side panel

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1218]
**Describe the bug**
Formula field value does not show up on the side panel
![image (1)](https://user-images.githubusercontent.com/307298/233309434-9b6b2685-e205-46b4-b12b-755b6fd321e3.png)

**To Reproduce**
1. Create a formula field
2. See the value in the table
3. Does not show up in the side panel

**Expected behavior**
A formula field value should be shown in both the main table and the side panel

**Comment by mnmt7** [comment]
@harinij I would like to work on this.

**Comment by jemiluv8** [comment]
@mnmt7 I've started working on it.

**Comment by mnmt7** [comment]
Hello @jemiluv8, I already made significant progress towards resolving the issue when I asked for the assignment and was just waiting for the assignment of the issue before creating a pull request.

However, I have a slight different way of implementing the solution for this issue. Specifically, I have taken care to ensure that the appropriate JSX component is rendered for each of the fields. While the generic TextField component may be suitable for Number and Text fields, it may not be the best solution for more complex fields such as Rating and Slider.

![screenshot](https://user-images.githubusercontent.com/107614965/233971322-6fcb585d-f54c-4fda-a3d1-1fd01414fb72.png)

By tailoring the rendered component to the specific field type, I believe that we can achieve a more efficient and effective solution to the issue.

**Comment by jemilu2** [comment]
@mnmt7  I agree. Your solution is superior. Kudos.

I kinda always assumed formula fields will always 
return something that is a number or text. I didn't look 
into the other "Field Types" that may be assigned them.

**Comment by mnmt7** [comment]
@jemilu2 I was of the opinion that since Lodash .isEqual() performs deep comparision, it will be automatically handled. 
`if (!isEqual(prev.field, next.field)) return false;`
However, I am open to the possibility that my assumption may have been incorrect.

**Comment by harinij** [comment]
Hi @mnmt7 and @jemilu2 thanks to you both for looking into this and submitting PR, appreciate the effort. Given that @mnmt7 had commented here first for the assignment, I have assigned the task now and we will be reviewing the PR and adding feedback soon.

**Comment by harinij** [comment]
Thanks @mnmt7 for your contribution 🎉
