### ISSUE TITLE
Import Wizard issue

### ISSUE THREAD

**Issue by Ken-JIAnomads** [rowyio/rowy#1224]
**Describe the bug**

Hi,

I tried to use the import wizard to import an existing Firebase database (with 1 test document).

I get completely through the import wizard including the final preview step which all seem fine. But when I hit "Finish",  it still won't load my existing firebase data.  The created rowy table shows up as "loaded all 0 of 1 row".

![Screenshot 2023-04-24 at 8 25 56 am](https://user-images.githubusercontent.com/130031825/233869433-039bd127-db3a-4a44-9756-8b65d75ae876.jpg)

![Screenshot 2023-04-24 at 8 19 05 am](https://user-images.githubusercontent.com/130031825/233869384-1008279d-94a6-4ec8-8c74-bb3aefc520c4.jpg)

**Expected behavior**
Existing firebase data show show up on Rowy database and I can visually amend/add to it.

**Additional context**

Further when I then try to add a new row I get an orange dot with comment.  "Row out of Order.  This row will not appear on the top of the table after you reload this page".  Why do I get this?

Appreciate your help. Thanks!

**Comment by bofeiw** [comment]
Currently, if filter or sort is applied to a table, it may not load all rows. We are working on improving UI to make it more transparent. Here is a similar thread: https://github.com/rowyio/rowy/discussions/1188

Out of order may show up for a couple of reasons as commented here: https://github.com/rowyio/rowy/blob/main/src/atoms/tableScope/rowActions.ts#L118
1. Add row to top is not selected.
<img width="408" alt="Screenshot 2023-04-24 at 07 03 02" src="https://user-images.githubusercontent.com/34177142/233870842-17306e36-b892-4bb4-a8a0-b5052b388fb9.png">

2. Some filters are set.

**Comment by Ken-JIAnomads** [comment]
Thanks.  That "To top" option was actually greyed out and no filters were set. 

But it somehow just fixed itself after the following;

- My firebase rules were out of date so I redeployed
- I created a new Rowy table with a different (unique?) name. i.e. Placeitem2

Not sure if it's one or both of those actions tho.

Thanks for your prompt help and reply!
