### ISSUE TITLE
Single and Multi select fields - edit for options

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1247]
**Describe the issue**
Currently, the single and multi-select field options, do not have an editing option. They need to be deleted and added again if you want to edit them.

**Solution**
Add the option to click on an option value and edit the value of the option in this modal for single and multi-select

<img width="978" alt="Screenshot 2023-05-06 at 1 36 07 pm" src="https://user-images.githubusercontent.com/307298/236597666-de7b5c9e-50fc-4855-bed6-b9409e565efe.png">

**Comment by harinij** [comment]
Tagging @mnmt7

**Comment by mnmt7** [comment]
@harinij Sure, I would like to work on this issue

**Comment by ashutosh887** [comment]
@harinij 
Should I work on this now if not resolved?

**Comment by harinij** [comment]
Hi @ashutosh887 this issue has been merged, closing this now.
