### ISSUE TITLE
JSON fields get imported as Strings

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1253]
**Describe the bug**
This is a generic import bug. Whenever the data is imported into the table (either via JSON, or CSV) the JSON objects get converted into Strings.

**To Reproduce**
1. Export any table with JSON field type, either via JSON or CSV.
2. Go to another table and import the exported data in step 1.
3. Check out the stringified JSON objects.

**Screenshots**

Exported JSON Data:
<img width="1139" alt="image" src="https://github.com/rowyio/rowy/assets/53828745/23797e8f-97e9-4315-a7b8-95cf107749c1">

Imported String data in JSON field type:
<img width="516" alt="image" src="https://github.com/rowyio/rowy/assets/53828745/43b0f54e-f919-4e21-a4de-395588ccc361">

**Comment by mnmt7** [comment]
@BeeBombshell, I followed the steps as mentioned but I am unable to recreate the issue.

**Comment by harinij** [comment]
@BeeBombshell @mnmt7 it appears that this issue only occurs during import to an existing table with a derivative column whose output is of the json type. Regular JSON type of import to a new table or existing json column works well.

Given that this is a very specific case and not the standard usecase of import to import values into a derivative field - lets close this issue for now.

**Comment by harinij** [comment]
@mnmt7 Since we have closed this issue, we have created [another issue](https://github.com/rowyio/rowy/issues/1264) with a similar problem with more detail and have assigned it to you in case you are interested in looking into it. Thank you.
