### ISSUE TITLE
Reference Field gets stored as a String in Firestore when imported

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1264]
**Describe the bug**
Import data has two bugs in relation to data parsing. 

### Reference field import issue
When importing the reference field - The data seems to be getting stored as a string in the Firestore document and the table cells remain blank. Gives an error in the side panel probably because it is stored as a string instead of a Firestore Reference.

**To Reproduce**
1. Export the data from a table having a Reference field type. (via CSV or JSON)
2. Import the data in a blank table. Select the column type of the document reference to be `Reference`.
3. See the blank columns for the reference column.
4. Open the side panel to add data and the error message in the field.

**Expected behavior**
The imported document reference data should be stored as `Reference` instead of `String`.

**Screenshots**
![image](https://github.com/rowyio/rowy/assets/53828745/5c3d80b0-a1da-4df5-9f64-605be3395d87)

<img width="1228" alt="image" src="https://github.com/rowyio/rowy/assets/53828745/5af94125-7758-4a69-9a29-08c772095e89">

### Import data to derivative field issue
Whenever the data is imported into the table (either via JSON, or CSV) the JSON objects if imported into `Derivative` field type then it instead of getting imported as JSON gets converted to String. Note this is only when the import is into a derivative field type of JSON. If it is a directly imported into JSON field then it works fine.

To Reproduce

Export any table with JSON field type, either via JSON or CSV.
Create a table with derivative field which has a return type JSON.
Import the CSV into that table mapping a JSON field to the derivative fied.
Check out the stringified JSON objects.
Screenshots

Exported JSON Data:
<img width="1139" alt="image" src="https://github.com/rowyio/rowy/assets/53828745/23797e8f-97e9-4315-a7b8-95cf107749c1">

Imported String data in Derivative with return field type JSON:
<img width="516" alt="image" src="https://github.com/rowyio/rowy/assets/53828745/43b0f54e-f919-4e21-a4de-395588ccc361">

**Comment by harinij** [comment]
fyi @mnmt7

**Comment by BeeBombshell** [comment]
Thanks, @mnmt7 for taking the time to test this issue. I tried it again, not able to replicate this issue anymore. The problem might have been specific to my data format. It seems that the issue might not be a general bug but rather a localized occurrence.
Will look more into the situation to identify any potential factors that might have caused this. Closing this for now...
