### ISSUE TITLE
Client Offline Error

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#1289]
Faced by: Lumberpack#9340, GabrielFranco#1702, MoMo#9788, paulefde#8975 on [Discord Support Forum](https://discord.com/channels/853498675484819476/1109429020896014439/1109429020896014439).

**Describe the bug**
I always get this error while trying to import csv file and match the fields. I have checked this on multiple browsers and on numerous WiFi even and the error still persists. Other web pages work fine. I even tried using VPN, but it's the same. It shows that you're offline or on a blank page. 

![image](https://github.com/rowyio/rowy/assets/53828745/9ff69946-a724-4dfe-a2f4-ba9647e06964)

And add to that, when I created the project and imported my csv I have the "You're offline" icon all the time, and records that I imported a few days ago do not appear while I've checked it now.

**Additional context**
After a thorough investigation, we have identified the cause to be a third-party package: [react-detect-offline](https://github.com/cwise89/react-detect-offline) that is no longer receiving active maintenance.

**Comment by harinij** [comment]
Fixed with https://github.com/rowyio/rowy/pull/1285
