### ISSUE TITLE
Reference field to allow copy/paste on the Table UI

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1319]
**Is your feature request related to a problem? Please describe.**
Currently the `reference` field does not allow for copy-paste in the Table UI. You can copy-paste on the side panel with validation. **[See video.](https://jam.dev/c/027cccd5-59d2-4eb1-b4ed-9d63e4026cc1)**

**Describe the solution you'd like**
Allow for copy-paste of the `reference` field on the Table UI **with validation** similar to how the side panel has validation in place in case someone tries to paste an invalid reference field value.

**Comment by orchard800** [comment]
When will this be implemented please?? I need it for my current project :-)

**Comment by ashutosh887** [comment]
@harinij @BeeBombshell 
I see this bounty has been claimed... Is it resolved or still there's some scope to improve?

**Comment by harinij** [comment]
Hi @orchard800 this has been pushed to the RowyApp. Previously it was available only on the side drawer now you can copy paste on the main table. thanks to @mnmt7's contribution.

https://github.com/rowyio/rowy/assets/307298/2ed25a14-2b01-49cb-ad54-67d8eabfde49

Thanks @ashutosh887 for pointing it out, closing the issue now.
