### ISSUE TITLE
Ability to add images to richtext field

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1323]
**Is your feature request related to a problem? Please describe.**
Currently, the richtext fieldtype does not natively support the upload of images feature. The images needs to be uploaded / hosted elsewhere like an image column and copy pasted into the richtext field. We need the ability for richtext fieldtype to have an upload image option.

**Describe the solution you'd like**
There should be an upload image option in the richtext field, that allows for images to be uploaded to Cloud storage - similar to how `Images` or `Files` column currently work.

Current richtext field implementation should support image https://www.tiny.cloud/docs/plugins/opensource/image/

**Comment by ParbhatKataria1** [comment]
Hi, @mnmt7! Congratulations on your pull request for the issue. 
I am new to open source. I saw your contribution, and you have added more environment variables to it. If you don't mind, can you please answer these questions?
How will the team set these environment variables?
Should we notify them about these new variables?
Thanks!

**Comment by harinij** [comment]
Thanks @mnmt7 🎉
