### ISSUE TITLE
How To Add ID Metadata When Importing

### ISSUE THREAD

**Issue by chaplaindan** [rowyio/rowy#1329]
### Discussed in https://github.com/rowyio/rowy/discussions/1328

<div type='discussions-op-text'>

<sup>Originally posted by **chaplaindan** July  1, 2023</sup>
I am really enjoying the process of learning Rowy. **It's a great product and has a lot of depth.** 

I created a Rowy.io project and created a table called 'company' which had only two columns: 1. companyName and, 2. companyId. The companyId column is using a field type set to metadata ID. 

When I add a new row and type something in companyName, Rowy.io automatically adds an ID in in the companyId cell. 
But **when I import a list of companies in the table using CSV**, it doesn't add anything in the companyId cell. 

Q: when importing data into a table with an ID field, do you have to provide your own ID or is there a method to add/update the IDs afterward? 
</div>

**Comment by harinij** [comment]
Closing this as has been answered here: https://github.com/rowyio/rowy/discussions/1328#discussioncomment-6361024
