### ISSUE TITLE
CORS error when trying to create a project

### ISSUE THREAD

**Issue by pierpo** [rowyio/rowy#1340]
**Describe the bug**

When I try to create a project, I get the following error.

**To Reproduce**

I am not sure how you can reproduce.

1. I created an account
2. I started a firebase project following the instructions
3. I tried to link the project to my account
4. I started getting errors
5. When going back and forth, I have errors on other pages.

**Expected behavior**

Well I should be able to create a project...

**Screenshots**

On the project linking after account linking

<img width="1511" alt="image" src="https://github.com/rowyio/rowy/assets/6313316/476b2b43-7483-4a11-9c24-81e1d1262ff7">

After going back and forth

<img width="1505" alt="image" src="https://github.com/rowyio/rowy/assets/6313316/d36ac07d-8951-4dca-b6a2-4b14f0920a3e">

**Rowy Run version**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 114

### Note

I just tried on firefox. Same issue!

<img width="1507" alt="image" src="https://github.com/rowyio/rowy/assets/6313316/82a6913b-735d-47f5-8d96-7acc20b6ab4a">

**Comment by harinij** [comment]
Thanks @pierpo closing this now as it seems to be an isolated issue.
