### ISSUE TITLE
Bug: Offline error

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1347]
**Describe the bug**
We are seeing occasional cases where user gets "You're offline" error and after that, they get stuck in that state, even though they are online and have internet connectivity.

This is a bug we have not been able to actively reproduce but have a bunch of users facing and complaining about [here](https://discord.com/channels/853498675484819476/1125514154489425940).

Previously this issue was seen [here](https://github.com/rowyio/rowy/issues/1289#issue-1751327460) and resolved. However, this need further investigation to resolve the issue completely.

**Expected behavior**
Check the logic where "You're offline" comes into play and debug if there is any scenario where it is falsely triggered. Remove this logic from places where it is not required. This error should not come in when the user is online and the state should not be stuck there.

**Screenshots**
![image](https://github.com/rowyio/rowy/assets/307298/c27c6cbd-a432-4d9e-b7cf-6e331f2a1dcd)

**Additional context**
Feel free to discuss any technical details with the team on [discord](rowy.io/discord) if you want to chat for further clarity as this is an ambitious bug.

**Comment by hrutik7** [comment]
Hey ,
can you assign this to me ?

**Comment by vats147** [comment]
@harinij 
Can we make 5 second timer whenever user again come to online then we automatically reload page after 5 second?
It will decrease with time.

**Comment by feliciien** [comment]
can I work on this?

**Comment by hrutik7** [comment]
Just for the context 
The first priority here is reproduce this bug in local dev .
anyone who want to contribute on this specific issue you can follow the support channel discussion that will be really helpful :)

**Comment by dylanrod21** [comment]
@feliciien I've added some additional details in the comments on the pull request here https://github.com/rowyio/rowy/pull/1352

**Comment by ashutosh887** [comment]
@harinij @BeeBombshell  Let me attempt this one if not resolved yet!

**Comment by ashutosh887** [comment]
@harinij @BeeBombshell Please update me on this so I'll proceed

**Comment by harinij** [comment]
Hi @ashutosh887 we have an open PR here https://github.com/rowyio/rowy/pull/1352 however since we have not be able to replicate this fully in local env and the issue seems to happen to only a small set of users we are still having this issue open as there is no complete solution yet.

@vats147 and @dylanrod21 thanks for investigating this and your contribution, we are currently reviewing the PR and will post comments on it soon.

**Comment by Anurag00321** [comment]
Hey @harinij , I guess #1285 actually solves this issue. Maybe it still occurs because of the way the project is branched. As the branches 'develop' or 'rc' are way ahead of main branch. Like I cloned the  main branch, I was able to reproduce the error, then I checked with 'develop' branch, then no such error was there.

**Comment by il3ven** [comment]
> I guess https://github.com/rowyio/rowy/pull/1285 actually solves this issue.

@Anurag00321 The offline error is shown when the user is offline or the user can't connect with rowy's server. The PR that you have mentioned fixes the first problem but still a few offline errors remain due to the second reason.

**Comment by harinij** [comment]
This issue had been resolved via a backend update on the endpoint URL. Closing this as it out of scope now.
