### ISSUE TITLE
popup overlaping on tools

### ISSUE THREAD

**Issue by vats147** [rowyio/rowy#1351]
**To Reproduce**
1. Click on `create table`
2. See popup  on left corner

**Expected behavior**
This `creating table` popup should be in right corner so it will not overlaping tools so user can easily access them 

**Screenshots**
![image](https://github.com/rowyio/rowy/assets/89577062/892d2213-f218-46da-9b07-eea5d2780376)

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser : Chrome

**Comment by janvi01** [comment]
hey, I just reproduce this issue. Can I work on this? @vats147

**Comment by vats147** [comment]
Yes you can @janvi01 but make sure this is first confirm by moderator

**Comment by janvi01** [comment]
> Yes you can @janvi01 but make sure this is first confirm by moderator

@harinij @BeeBombshell kindly look.

**Comment by harinij** [comment]
Hi @vats147 @janvi01 this issue is still unscoped. Moving to the right side wouldn't work all the time as the create button icon is there. For now, will be closing this issue as this does not cause any actual issue and the popup snackbar disappears after a few seconds anyway.

**Comment by vats147** [comment]
@harinij It is playing some kind of role when it comes to UI/UX desgin.
