### ISSUE TITLE
FEAT: Array column should be filterable

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1382]
**Is your feature request related to a problem? Please describe.**
Currently, the filter feature does not work for the newly added "Array" column type.

**Describe the solution you'd like**
Allow for the Array column to be filterable.
<img width="647" alt="Screenshot 2023-08-17 at 1 06 22 pm" src="https://github.com/rowyio/rowy/assets/307298/c68f0ec4-43be-4f6c-83f5-2546330a5339">

**Comment by rishi-raj-jain** [comment]
/attempt #1382 (already submitted the PR as above)
