### ISSUE TITLE
Enable copy option for ID column from the context meny

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1403]
**Is your feature request related to a problem? Please describe.**
Currently, the ID column in the table, does not have copy option in the right click context menu.
<img width="280" alt="Screenshot 2023-09-07 at 12 56 40 pm" src="https://github.com/rowyio/rowy/assets/307298/5f9cf1ba-21d0-457b-ba5e-4f7100e80748">
 
**Describe the solution you'd like**
Add the ability to copy values from the ID column from right-click menu

**Comment by AnushDeokar** [comment]
I would like to take this issue. Just to confirm, for the above example it should copy ico.......g1 right?

**Comment by shamsmosowi** [comment]
its currently solved on [dev already](https://github.com/rowyio/rowy/commit/a2806a7c31c6526ffd2f0492657a36470f45cf15)
