### ISSUE TITLE
Table name textbox UI error on first click

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1409]
**Describe the bug**
When opening the table settings and trying to edit the Display name, it glitches [see video](https://jam.dev/c/9f03ecaf-be06-4d1f-ab7c-52e35afff3aa). Works after you try to change any other field like description for example.

**Expected behavior**
Display name should be editable in the table settings

**Comment by subhajit20** [comment]
@harinij Hey, want to help.
Can you assign it to me.

**Comment by harinij** [comment]
Thanks @subhajit20 have assigned to you now.

**Comment by subhajit20** [comment]
what to put in `firebase-service-account.json` file
<img width="775" alt="Screenshot 2023-09-12 at 12 45 42 PM" src="https://github.com/rowyio/rowy/assets/99127578/1a057ee8-1a04-459f-82ab-7ce1466d5693">

**Comment by subhajit20** [comment]
@harinij hey I have tested that issue locally, It was working fine but on the main website, it is having the problem.

**Comment by AnushDeokar** [comment]
Hey Guys, I was able to locally recreate this issue and was able to come up with a small fix. Opening a PR for the same.
