### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by subhajit20** [rowyio/rowy#1410]
**Describe the bug**
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

**Screenshots**
![Rowy - Low-code backend on Google Cloud and Firebase - Google Chrome 12-09-2023 19_07_43](https://github.com/rowyio/rowy/assets/99127578/5e359421-0c34-409f-8326-05263f32bf57)

**Comment by harinij** [comment]
Duplicate issue addressed here: https://github.com/rowyio/rowy/issues/1404
