### ISSUE TITLE
No tooltips showing for Table settings header buttons

### ISSUE THREAD

**Issue by janvi01** [rowyio/rowy#1411]
**Describe the bug**
While hovering over the buttons on the top right in table settings, nothing shows.

**Expected behavior**
There should be a tooltip for every icon button to enhance user experience.

**Screenshots**

https://github.com/rowyio/rowy/assets/34344234/ac430b77-9538-40ea-9269-3d254b21c281

**Comment by janvi01** [comment]
I just noticed, there is no tooltip for table card buttons as well.

<img width="401" alt="Screenshot 2023-09-13 at 6 27 11 PM" src="https://github.com/rowyio/rowy/assets/34344234/cc195b81-1e35-4c83-b8aa-66cef2c2728d">

I would like to work on this. @harinij

**Comment by harinij** [comment]
Hi @janvi01 - thanks for this, I have assigned this to you if you want to take a crack at this.

**Comment by rabinnepal** [comment]
hi if this is still open i would like to work on this

**Comment by janvi01** [comment]
Hey @rabinnepal I am working on this, you can look or create any other issues.
