### ISSUE TITLE
Build your app Link not working

### ISSUE THREAD

**Issue by ManishBisht777** [rowyio/rowy#1424]
**Describe the bug**

When clicking on the `Build Your App` Link it goes to other page

**To Reproduce**
1. Go to 'https://www.rowy.io/'
2. Click on 'Build Your App'
3. See error

**Expected behavior**

**Screenshots**

![image](https://github.com/rowyio/rowy/assets/89926834/0b19e7ee-c5b3-45a9-a455-b491d8678fd5)
![image](https://github.com/rowyio/rowy/assets/89926834/19ee1d79-8620-43a1-b971-39b875466a43)

**Rowy Run version**
If applicable, share the Rowy Run version from your project settings.

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser: Chrome
 - Version: 116.0.5845.188 (Official Build) (64-bit)

**Additional context**

**Comment by Chadha93** [comment]
Hi @ManishBisht777, please check the site again, it is working fine.

**Comment by ManishBisht777** [comment]
Works now :) closing this as completed
