### ISSUE TITLE
Add confirmation modal for bulk deletion of rows

### ISSUE THREAD

**Issue by janvi01** [rowyio/rowy#1455]
**Is your feature request related to a problem? Please describe.**
Currently, the bulk deletion of rows button does not need confirmation and ends up deleting the row immediately. This feature needs a confirmation message similar to the delete single row.

**Describe the solution you'd like**
Add a confirmation dialog that requires the user to confirm the bulk deletion of the row.

**Screenshots**

<img width="644" alt="Screenshot 2023-10-30 at 11 46 03 AM" src="https://github.com/rowyio/rowy/assets/34344234/03a410f5-d266-47d3-af10-7fbbb4d4dc71">

**Comment by janvi01** [comment]
@harinij Kindly look at the issue, I would like to work on this.

**Comment by DivvSaxena** [comment]
is anyone still working on this issue?

**Comment by Chadha93** [comment]
> is anyone still working on this issue?

Hi @DivvSaxena, there is already a linked PR.

**Comment by DivvSaxena** [comment]
Ohkk

**Comment by DivvSaxena** [comment]
Hey @Chadha93 , any other issues that I can contribute to get into this ecosystem?

**Comment by Chadha93** [comment]
> Hey @Chadha93 , any other issues that I can contribute to get into this ecosystem?

@DivvSaxena https://github.com/rowyio/rowy/issues

**Comment by janvi01** [comment]
Hi @Chadha93 the issue has been completed
