### ISSUE TITLE
Bug: Filter "is not empty" doesn't work as expected 

### ISSUE THREAD

**Issue by janvi01** [rowyio/rowy#1459]
**Describe the bug**
While applying the filter "is not empty" on any column, either it just keeps loading or gives an error.

**To Reproduce**
1. Apply the filter "is not empty" operator inside the filter modal in any column of your table.

**Expected behavior**
It should show the data according to the filter.

**Screenshots**

<img width="1792" alt="Screenshot 2023-11-01 at 4 40 15 PM" src="https://github.com/rowyio/rowy/assets/34344234/78c9867e-265d-4aa4-a550-ab01951a6a15">

<img width="1258" alt="Screenshot 2023-11-01 at 4 40 54 PM" src="https://github.com/rowyio/rowy/assets/34344234/e827885c-4a9c-41e1-ac54-20ea3c7a2393">

**Comment by janvi01** [comment]
I would like to work on this.

**Comment by I-MirzaBaig** [comment]
Can i work on this issue..?
I hope i can provide minimalistic solution to it, upon further discussion...

**Comment by Chadha93** [comment]
> @Chadha93 I would like to work on this.

Hi @janvi01, sure feel free to make a PR, I can confirm this issue.

**Comment by Chadha93** [comment]
@janvi01 Here is a more detailed log of the bug: `{"name":"FirebaseError","message":"initializeFirestore() has already been called with different options. To avoid this error, call initializeFirestore() with the same options as when it was originally called, or call getFirestore() to return the already initialized instance.","stack":"FirebaseError: initializeFirestore() has already been called with different options. To avoid this error, call initializeFirestore() with the same options as when it was originally called, or call getFirestore() to return the already initialized instance.","code":"failed-precondition"}`.

**Comment by bofeiw** [comment]
Potentially related to: https://github.com/rowyio/rowy/pull/1390 and https://github.com/rowyio/rowy/pull/1482

**Comment by janvi01** [comment]
I have started working on this.

**Comment by il3ven** [comment]
> I have started working on this.

@janvi01 Thanks for reporting this bug. I saw your comment after I opened a PR for this.

**Comment by janvi01** [comment]
oh no problem @il3ven
