### ISSUE TITLE
Bug with the bulk selection column with freeze columns

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1463]
**Describe the bug**
Bulk selection checkboxes option column is not fixed and it causes issues when horizontal scrolling with freezed columns. See video for explanation.

**To Reproduce**
See the recording
https://github.com/rowyio/rowy/assets/307298/7f6fda8a-9081-4a4d-88ae-01877d55bfbc

**Expected behavior**
Bulk selection options column should be fixed in the table.

**Comment by janvi01** [comment]
@harinij I would like to work on this. Please assign me.

**Comment by AnushDeokar** [comment]
/attempt #1463

Hey @harinij @janvi01, By looking at the previous issues I noticed that issues with bounties are not assigned and they are given on first successful attempt basis so as I started working on it as soon as it came without asking to assign. If this is not the case then kindly ignore my attempt. Thanks.

**Comment by janvi01** [comment]
@harinij I submitted a PR. Thanks for assigning me.

**Comment by il3ven** [comment]
@harinij I have merged https://github.com/rowyio/rowy/pull/1466 and closed others. You can close the issue and pay the bounty.
