### ISSUE TITLE
Copy paste in the filter field also updates the value of the cell if highlighted

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1467]
**Describe the bug**
When you are pasting something in a filter field it also pastes in a feld in Rowy if its selected. 

**To Reproduce**
See video: 
https://github.com/rowyio/rowy/assets/307298/585db437-674a-4dfa-b95a-951cf1c6a146

**Expected behavior**
The paste should only be in the filter field when the filter is open and not in the cell of the table

**Comment by janvi01** [comment]
@harinij I would like to work on this.

**Comment by janvi01** [comment]
@harinij I see this issue occurs if you try to paste anywhere in the rowy app when the cell is highlighted, it is not just specific to while pasting in the filter field.

Another case example -

<img width="925" alt="Screenshot 2023-11-06 at 4 44 32 PM" src="https://github.com/rowyio/rowy/assets/34344234/07986d4a-2a23-4ee7-a9f3-e65e11ea0e10">

**Comment by Min2who** [comment]
is this issue closed?

**Comment by I-MirzaBaig** [comment]
Has the issue resolved?
If not, can you assign me?

**Comment by Chadha93** [comment]
Hi @I-MirzaBaig @Min2who, Yes it's resolved https://github.com/rowyio/rowy/pull/1473 (linked PR).

Feel free to check more issues on - https://github.com/rowyio/rowy/issues

**Comment by I-MirzaBaig** [comment]
Alright😉

**Comment by harinij** [comment]
Hi @janvi01 thanks for your contribution 🎉 bounty has been rewarded now.
