### ISSUE TITLE
error TS2304: Cannot find name 'RTCErrorDetailType'.

### ISSUE THREAD

**Issue by frank-bee** [rowyio/rowy#1471]
**Describe the bug**
I get this error after I deleted a cloudfunction completely and now trying to re-compile and deploy it

**Rowy Run version**
latest? where can I change that

**Comment by frank-bee** [comment]
suddenly this issue is gone (?)

**Comment by Chadha93** [comment]
> suddenly this issue is gone (?)

Good to hear. Closing this one.

**Comment by frank-bee** [comment]
@Chadha93 it had to do with this issue which is still there:
https://github.com/rowyio/rowy/issues/1462
