### ISSUE TITLE
[UI] [BUG] - Filters in sub-table keeps refreshing

### ISSUE THREAD

**Issue by Chadha93** [rowyio/rowy#1478]
**Describe the bug**
When adding/removing a Filter to a sub-table, the page is getting into loops and refreshes. It is not updating the filter value on Firestore.

https://github.com/rowyio/rowy/assets/65453826/6f06ff7f-ee98-45f6-9854-6c8d9688899b

**To Reproduce**
1. Create a table - https://docs.rowy.io/how-to/create-table
2. Add a suitable - https://docs.rowy.io/field-types/array-subtable#creating-an-array-sub-table
3. Add and remove filter in the sub-table. 

**Expected behavior**
On addition or removal of any filter it should also update the filter value from the Firestore array. Which should then update the value in Rowy sub-table filters. 

**Rowy Run version**
Rowy - V3.0.0

**Comment by Wr4th100** [comment]
@harinij, the PR got merged, could you please close this issue?

**Comment by harinij** [comment]
Thanks @Wr4th100 for the contributions. Closing this now.
