### ISSUE TITLE
Add a delete/remove icon in Sorted button chip

### ISSUE THREAD

**Issue by janvi01** [rowyio/rowy#1479]
**Is your feature request related to a problem? Please describe.**
While applying sorting in columns, a sorting chip/ button appears on the top and if a user wants to remove the sorting, the chip has to be clicked first and then delete.

**Describe the solution you'd like**
Add a delete icon beside sorted just as we have for the filter button to enhance user experience.

Filter button with delete icon -

<img width="570" alt="Screenshot 2023-11-10 at 12 01 39 PM" src="https://github.com/rowyio/rowy/assets/34344234/7616e4e7-0db5-42a3-b8c6-c04a8fc81db8">

Sorted button -

<img width="570" alt="Screenshot 2023-11-10 at 12 02 00 PM" src="https://github.com/rowyio/rowy/assets/34344234/65aadf8a-ed93-4062-942a-f10864489e26">

**Comment by nikhilgupta58** [comment]
I am picking this issue.

**Comment by nikhilgupta58** [comment]
After careful consideration and reviewing the existing functionality, it seems that we already have robust options for users to dis-select sorting:

1. **Delete CTA Beside Every Sorting**: A delete CTA is conveniently placed beside each sorting option for quick removal.

2. **Clicking Sort Button Again**: Users can also disable sorting by clicking the same sort button they used to enable it initially.

Given these accessible and intuitive options, it appears that introducing an additional cross (delete) CTA might be redundant and could potentially clutter the user interface.

Please refer the attachment!!

cc @Chadha93 

https://github.com/rowyio/rowy/assets/36965562/102819c5-7213-48b0-b3fc-b7396e77afb1

**Comment by Chadha93** [comment]
> After careful consideration and reviewing the existing functionality, it seems that we already have robust options for users to dis-select sorting:
> 
> 1. **Delete CTA Beside Every Sorting**: A delete CTA is conveniently placed beside each sorting option for quick removal.
> 2. **Clicking Sort Button Again**: Users can also disable sorting by clicking the same sort button they used to enable it initially.
> 
> Given these accessible and intuitive options, it appears that introducing an additional cross (delete) CTA might be redundant and could potentially clutter the user interface.
> 
> Please refer the attachment!!
> 
> cc @Chadha93
> 
>  Screen.Recording.2023-12-27.at.10.16.06.PM.mov

As the sorting chip servers both propose, to update the sort and column with deletion, the current UX is correct. Closing this issue.
