### ISSUE TITLE
BUG: Filter on the table works, but the same applied to the Table Filter doesn't

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1483]
**Describe the bug**
When you filter by a value in the table it works as expected. However if you try to apply the same filter at table level to all users using that table as an ADMIN user - it does not work.

**To Reproduce**
See video

https://github.com/rowyio/rowy/assets/307298/7a57493c-958f-41aa-9261-378e2d162716

**Comment by ezhil56x** [comment]
Hello @harinij 👋🏻,
I would like to work on this issue!

**Comment by janvi01** [comment]
@harinij I am not able to reproduce this issue, the case mentioned works fine.

**Comment by ezhil56x** [comment]
@harinij I have setup my local dev env and I'm unable to reproduce this issue


https://github.com/rowyio/rowy/assets/103899034/f0f40c5e-60c8-4e81-954e-13347b3fe47b

**Comment by zeeshan1212** [comment]
> 💡 @janvi01 submitted a [pull request](https://github.com/rowyio/rowy/pull/1504) that claims the bounty. You can [visit your bounty board](https://console.algora.io/org/rowyio/bounties) to reward.

@janvi01 I've already submitted pull request for this and worked on this.

**Comment by zeeshan1212** [comment]
@harinij the PR got merged, could you please close this issue?
