### ISSUE TITLE
Sending Date using Webhook not working

### ISSUE THREAD

**Issue by abdoil** [rowyio/rowy#1487]
**Describe the bug**
i was trying to send data to rowy via webhook, all the other data are sent successfully except for Date, I tried sending as an object like this
```"posted":{"seconds":1681272000,"nanoseconds":0}```
and also in the format as yyyy-MM-dd. but still shows as blank. Here is a screenshot of how the data is

![image](https://github.com/rowyio/rowy/assets/85382720/ac429b90-54da-4ba1-8519-6ae31a0ef0de)

**To Reproduce**
Trying by sending the date as object to Webhook

**Expected behavior**
Nothing shows (Empty) 

**Rowy Run version**
Cloud Version

**Comment by uudens** [comment]
I was able to get it working using the [Timestamp](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Timestamp) class.  
Try to put something like this inside your webhook body:  

```ts
const { default: { Timestamp } } = await import("@google-cloud/firestore");
const ts = Date.now();
return { posted: Timestamp.fromMillis(ts) };
```

**Comment by Chadha93** [comment]
> I was able to get it working using the [Timestamp](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Timestamp) class. Try to put something like this inside your webhook body:
> 
> ```ts
> const { default: { Timestamp } } = await import("@google-cloud/firestore");
> const ts = Date.now();
> return { posted: Timestamp.fromMillis(ts) };
> ```

Thanks @uudens.
@abdoil, You can follow the above approach to solve this, closing this issue. Thanks.
