### ISSUE TITLE
Error while importing CSV to a table

### ISSUE THREAD

**Issue by mtalha101** [rowyio/rowy#1503]
**Describe the bug**
I'm trying to upload a test CSV to my Rowy Table in order to test if batch import is working as expected. During the process, I am selecting a column for Document IDs. The column contains strings like `iRjLMgqEa3YeshpWugXF `, `vlNhLqhxaWDnxSXDdkLu `. The error I'm getting is `n.charAt is not a function`. When trying to batch import CSV using Auto-Generated Document IDs it works fine, but while selecting a specific column leads to this error.

**Expected behavior**
The table should be able to import CSV by selecting a specific column to generate document IDs.

**Screenshots**

<img width="1440" alt="Screenshot 2023-12-07 at 6 01 32 AM" src="https://github.com/rowyio/rowy/assets/61347696/b3782f0b-1071-40a2-9a74-23b71cf8c7dc">

**Desktop:**
 - OS: macOS
 - Browser Chrome

**Comment by nikhilgupta58** [comment]
Is anyone working on this issue?

**Comment by Chadha93** [comment]
Hi @nikhilgupta58, thanks for volunteering for the issue, it is already resolved here - https://github.com/rowyio/rowy/pull/1514. 

Feel free to take more issues.

**Comment by nikhilgupta58** [comment]
Sure
