### ISSUE TITLE
Unable to connect an existing firebase project "load failed"

### ISSUE THREAD

**Issue by thibautvdu** [rowyio/rowy#1505]
**Describe the bug**
Cannot connect an existing firebase project.
When clicking on 'Confirm to use the project', the error 'load failed' is returned.
Console errors seem to point out to cors issue

**To Reproduce**
1. Go to "Your workspace"
2. Click on "Create Project"
3. Input project name ("coco")
4. Choose firebase as datasource and continue
5. Login with google account that has full admin rights on the project
6. Select project
7. Click on 'Confirm to use the project'

**Expected behavior**
Project should be connected

**Screenshots**
<img width="1027" alt="Capture d’écran 2023-12-13 à 11 15 03" src="https://github.com/rowyio/rowy/assets/8306587/cdd3f67f-5cf4-4d70-aeeb-c42fe7eed0e8">
<img width="1510" alt="Capture d’écran 2023-12-13 à 11 23 19" src="https://github.com/rowyio/rowy/assets/8306587/e299ecdd-5d62-4ee5-b33f-a2f60a923de9">

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Safari, Chrome

**Comment by Maqurez** [comment]
The same problem on Windows/Edge
Even when creating a new project via Rowy - a new project is created in Firebase but fails to load

**Comment by thibautvdu** [comment]
@Maqurez 

A workaround is connecting / signing up on Rowy with the exact same google account that you later use to connect to your firebase project (so the admin GA). Definitely a bug.

**Comment by Chadha93** [comment]
Hi @Maqurez and @thibautvdu, we are tracking this bug and will be fixing this soon from the backend. Thanks @thibautvdu for sharing the workaround for now. :+1:

**Comment by bofeiw** [comment]
We have fixed this issue that didn't work if you use a different account for project setup than the one used to sign in Rowy. Thanks all for the feedbacks.
