### ISSUE TITLE
Error Setting Firestore/Storage Rules when Connecting Rowy to Firebase

### ISSUE THREAD

**Issue by edwingenio** [rowyio/rowy#1511]
I'm experiencing the same, I tried everything even deleting everything related to you on my end. It looks like in your backend I have a project active, which doesn't let me delete my account. It came after I deleted my project to start from scratch twice. 
![image](https://github.com/rowyio/rowy/assets/23000321/d912ae88-ee68-425d-af0d-6d868901a015)

### Discussed in https://github.com/rowyio/rowy/discussions/1457

<div type='discussions-op-text'>

<sup>Originally posted by **hanmangt** October 30, 2023</sup>
We're in the process of setting up a new project and we're encountering an issue while attempting to connect Rowy with our Firebase. The specific error message we're receiving is: "Error setting Firestore/Storage rules: Requested entity was not found."

We've checked that the Firebase rules are configured. Any ideas on what we might have missed to make the Rowy connection work?
![image](https://github.com/rowyio/rowy/assets/149450909/d02981ee-2896-4b2c-8460-5bc7611298f2)
</div>

**Comment by Chadha93** [comment]
Hi @edwingenio, Thank you for creating an issue here, we are tracking this issue and will update you on the fix.

**Comment by edwingenio** [comment]
Thanks. I found that exporting the database, and then deleting and creating a new one worked to create the project. So, it only seems like the issue is with a runtime constraint that should've been conditional. It should be fixable rather quickly.

**Comment by Chadha93** [comment]
> Thanks. I found that exporting the database, and then deleting and creating a new one worked to create the project. So, it only seems like the issue is with a runtime constraint that should've been conditional. It should be fixable rather quickly.

Cool, closing this issue as tracked on Discussions.
