### ISSUE TITLE
BUG: copy/paste on Array Subtable filed gives an incorrect error

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#1523]
**Describe the bug**

Copy/pasting on array subtable has some issues. 

Issue 1
Copy/pasting the array subtable field is throws an error:
<img width="513" alt="Screenshot 2024-01-22 at 19 06 57" src="https://github.com/rowyio/rowy/assets/34177142/5b4b264d-95b6-4930-9fe4-8d7cb63ed747">

Issue 2
Copying fields inside array subtable works.
Pasting fields inside array subtable works but an error is displayed.
<img width="512" alt="Screenshot 2024-01-22 at 19 07 16" src="https://github.com/rowyio/rowy/assets/34177142/e08e3dc5-8070-47f2-9b7c-2142e6086364">

**To Reproduce**
1. On Rowy - create an array subtable field
2. Copy or paste the field, see issue 1
3. Go in to the subtable, create a text column and add a row
4. Paste some values in the text cell, see issue 2

**Expected behaviour**

The data type of [Array SubTable](https://docs.rowy.io/field-types/array-subtable) in FIrestore is [array of maps](https://firebase.google.com/docs/firestore/manage-data/data-types).
Issue 1: copy/paste on the array subtable should copy the array to clipboard or write values to Firestore, similar how JSON field works.

Issue 2: pasting into the fields inside subtable should continue to work without any errors displayed.

**Comment by Amanullah1002** [comment]
Let me try this issue /attempt #1523

**Comment by bofeiw** [comment]
Hi @anikdhabal and @ImamAbdullahKhan, I've updated the issue description to make the expected behaviour clearer, both PRs do not resolve the issue, please update, thank you.
