### ISSUE TITLE
Add fuzzy search to column type select popup

### ISSUE THREAD

**Issue by bofeiw** [rowyio/rowy#1529]
When selecting a [column type](https://docs.rowy.io/field-types/supported-fields) and search for "string", I expect it to show the text field options, but it shows empty results.
<img width="492" alt="Screenshot 2024-01-23 at 07 23 38" src="https://github.com/rowyio/rowy/assets/34177142/60e39f8c-a834-498d-babc-de91eb70d732">

Fuzzy search can be enabled in the column select popup. A possible package is [Fuse.js](https://www.fusejs.io/), we can define relevant keywords to associate to column types, for example:
```js
const columnTypes = [
  {
    id: "shortText",
    title: "Short Text",
    keywords: ["string", ...]
  },
  {
    id: "toggle",
    title: "Toggle",
    keywords: ["boolean", "switch", "true", "false", "on", "off"]
  },
  {
    id: "geoPoint",
    title: "Geo Point",
    keywords: ["location", "latitude", "longitude", "point"]
  },
  {
    id: "image",
    title: "Image",
    keywords: ["picture", ...]
  },
]
```

As a result, searching for "picture" will display "image" type, searching for "location" will display "geoPoint" type, for example.

And we can tolerate typos, searching for "strng" will display "shortText" type.

**Comment by mehulmathur16** [comment]
/attempt #1529 @harinij  Can this issue be assigned to me ?
Also, this is my first time contributing to rowy. Can you please tell how much time is given for closing an issue ?

**Comment by mehulmathur16** [comment]
@harinij @bofeiw the PR got merged, could you please close this issue?
