### ISSUE TITLE
Table Views: display same table with different column configs & sections

### ISSUE THREAD

**Issue by jonathan-chin** [rowyio/rowy#209]
first of all, this is a phenomenal project. we're looking at replacing our current reliance on Airtable with this because it has a large opportunity for being more powerful and functional.

I've discussed it with my team and there's one crucial feature that's holding us back: views. in production, we have a few views such as: 'volunteers', 'admin', 'Jon Chin', 'Marc and Melissa'. these views have different columns hidden.

is there any interest already in implementing something like this? what would be even better is if we can limit users to certain views, which is something Airtable doesn't do. for now, we just trust volunteers to only use the volunteers view.

I'd happy to contribute code to make this happen. just curious if such a feature is on your radar.

**Comment by notsidney** [comment]
Hi Jonathan, @shamsmosowi and I had a similar idea about displaying the same table with different column configs & different sections on the home page, then we could apply permissions based off each view/table alias. We haven’t built it yet

**Comment by harinij** [comment]
@jonathan-chin We finally have this feature released now. You can get the latest version of Rowy by using this easy deploy link on your Firestore project: [rowy.app/deploy](https://rowy.app/deploy). Try it out and we would love to get your feedback, join us on [Discord](https://discord.com/invite/B8yAD5PDX4) 🙏
