### ISSUE TITLE
How to add ConnectTable select?

### ISSUE THREAD

**Issue by leoruhland** [rowyio/rowy#238]
Hi! Congratulations on this great project.

I would like to know how I could add a simple relationship between 2 entities.

Example: Post and Categories.

I saw in the Roadmap that the following types of fields were made:

- single select reference (DocReference)
- multi select reference (DocReference)

But I can only add selects with static data added manually.

I'm probably forgetting something, but I read all the documentation and I couldn't understand how I can add such a field.

I'm sorry if it's a stupid question.

Thank you.

**Comment by notsidney** [comment]
Hi @leoruhland, thanks for your interest in Firetable! We currently do not have a guide on how to set up this field. It requires you to set up Cloud Functions and I don’t have the specifics for that at the moment. I’ll let you know here once we have a guide written.

**Comment by Arpiiitaaa** [comment]
May I take this up?

**Comment by harinij** [comment]
Hi @Arpiiitaaa Sure, I have assigned this to you. You can take a look at adding docs here in this [repo](https://github.com/rowyio/docs)

**Comment by harinij** [comment]
Closing out this old issue, we have documentation available [here](https://docs.rowy.io/field-types)
