### ISSUE TITLE
Deploy target firetable not configured for project

### ISSUE THREAD

**Issue by minuitagency** [rowyio/rowy#243]
**Describe the bug**
When trying to deploy firetable I get the following error:
```
Deploy target firetable not configured for project XXXX. Configure with:

  firebase target:apply hosting firetable <resources...>

```

**To Reproduce**
cd my project
firetable deploy

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macos

**Comment by notsidney** [comment]
Hi @minuitagency, please run the command listed by your terminal. I’ll have a look at how we can improve the CLI to prevent this from being a manual step.
