### ISSUE TITLE
Unable to deploy when there's already firebase hosting in use

### ISSUE THREAD

**Issue by elvisun** [rowyio/rowy#253]
**Describe the bug**
Have firebase hosting running my site already, trying to deploy firetable with the CLI.

```
PS C:\Users\1\Documents\Github\wish-list-share\admin_portal> firetable deploy
? Do you want to change your current host target (admin-dev.antaa.app)? Yes
? Where do you want to deploy?
  You can find your available sites or create a new one here:
  https://console.firebase.google.com/u/0/project/abc/hosting
  Enter your site name: abc
🥳  Firetable has been successfully deployed to
   https://abc.web.app
```

But after visiting the URL no firetable is found

**To Reproduce**
1. Create a project
2. Deploy something to firebase hosting
3. `firetable deploy`

**Expected behavior**
Show error and documentation on how to proceed.

**Comment by shamsmosowi** [comment]
Hi @elvisun 
are you able to find abc.web.app listed under your sites when you go to the hosting in the firebase console?
https://console.firebase.google.com/u/0/project/abc/hosting

**Comment by elvisun** [comment]
Yes I have firebase hosting setup to host a static site, so it points to the existing site

**Comment by shriharip** [comment]
yes, facing the same issue

**Comment by shriharip** [comment]
> yes, facing the same issue

saw that the projects id property is not set properly . setting it using the firebase cli command inside the www folder will help

**Comment by shamsmosowi** [comment]
You can use the deploy on cloud run button now, for more reliable simplified deployment experience
