### ISSUE TITLE
Logging into firetable replaces user's existing auth credentials

### ISSUE THREAD

**Issue by mtford90** [rowyio/rowy#264]
**Describe the bug**

Logging into firetable (using google auth) replaces other forms of authentication rather than adding to them. My user had password auth & phone number auth enabled but these were removed after logging into firetable.

**To Reproduce**

- Create an account on firebase with other forms of authentication e.g. password/phone number. 
- Log into firetable.
- Observe loss of other forms of authentication in the firebase console.

**Expected behavior**

User should have additional google auth credentials alongside those that are pre-existing.

**Comment by harinij** [comment]
@mtford90 This has been fixed in the recent release with support for multiple auth options. Give it a try with the easy deploy link: [rowy.app/deploy](https://rowy.app/deploy)
