### ISSUE TITLE
[UX] Add autofocus for corresponding cell when opening the right drawer

### ISSUE THREAD

**Issue by wzulfikar** [rowyio/rowy#266]
**Is your feature request related to a problem? Please describe.**
It doesn't relate to a critical problem but it could improve the UX of the app.

**Describe the solution you'd like**
When I click a long text or a rich text, the right drawer (the editor) will open automatically _but_ I still need to click the corresponding field to start editing. 

Is it possible to automate this? For example, when I click the "**AI Description**" cell, I expect the the right drawer will to be opened _and_ the cursor should be autofocused in the "**AI Description**" field without manually clicking it.

![firetable-ux-autofocus mov](https://user-images.githubusercontent.com/7823011/98906933-f4a6e600-24f8-11eb-82a2-34f0ef2b2453.gif)

**Describe alternatives you've considered**
I can't see any alternative except to manually click the AI Description input. I tried to press tabs to see if the focus eventually reach there but it's not.

**Comment by notsidney** [comment]
@wzulfikar This has been on our to-do list for a while, but we’ll be working on consolidating column/cell type code for the table, side drawer, and settings first.

**Comment by wzulfikar** [comment]
Cool! Thanks for the info. Looking forward to it 🚀

**Comment by harinij** [comment]
Released
