### ISSUE TITLE
Custom document IDs

### ISSUE THREAD

**Issue by a-Leong** [rowyio/rowy#269]
Related: #234 

**Is your feature request related to a problem? Please describe.**
Currently there is no way to use a custom doc ID when creating a new row. My project utilizes custom doc IDs in some cases, and I would like to be able to handle these in Firetable.

**Describe the solution you'd like**
When creating a new row, an option provided to use a custom ID instead of the default generated ID.

**Comment by tv42** [comment]
I have a project that uses a DNS domain name as a key in one place, to ensure only one owner can claim a domain successfully. That's the only mechanism I know of in Firestore to ensure uniqueness. I'm sure others have similar needs.

**Comment by notsidney** [comment]
This was released in v2.2.0
