### ISSUE TITLE
Wiki section on updating firetable is confusing

### ISSUE THREAD

**Issue by jfr3000** [rowyio/rowy#296]
Hi!

The wiki section on [updating firetable](https://github.com/AntlerVC/firetable/wiki/Updating-Firetable#rebuild-and-redeploy-firetable) states that users should run `firetable build`, but that command doesn't exist in CLI v1.1.6 ?
When I only run `deploy` it doesn't seem like there is an updated version (at least the bug that's been fixed is still there...) On that note, it would be nice if firetable could display its version somewhere?

Is there something I'm missing? Thanks so much!

**Comment by harinij** [comment]
Hi @jfr3000 we have retired the CLI command and moved towards this quick deploy link to get you set up fast and the updates should be far more easier. Give it try here: [1-click deploy](https://rowy.app/deploy)
