### ISSUE TITLE
"FIRETABLE START" command not working

### ISSUE THREAD

**Issue by T4533N** [rowyio/rowy#303]
![image](https://user-images.githubusercontent.com/44163644/109660293-e0afee80-7b92-11eb-96ba-f5df03f2ca7c.png)

**Comment by turnono** [comment]
Use node v12

**Comment by taseentanvir** [comment]
![image](https://user-images.githubusercontent.com/44163644/109715445-dbbc6080-7bcd-11eb-9a39-26a4067261c3.png)

**Comment by Gcarter17** [comment]
did you ever find the fix for this?

**Comment by Gcarter17** [comment]
Uninstalling node v14 and getting v12 worked for me https://nodejs.org/en/blog/release/v12.13.0/

**Comment by shriharip** [comment]
I think this is a workaround. But need a real solution..

**Comment by bofeiw** [comment]
Try this before running firetable:
```bash
nvm install 12
nvm use 12
```

**Comment by harinij** [comment]
We have retired the CLI command and moved towards an easy deploy link to get you set up fast. Give it try here: [1-click deploy](https://rowy.app/deploy)

@Gcarter17 @turnono @T4533N 🙏
