### ISSUE TITLE
Make JSON field's structure inheritable in new row

### ISSUE THREAD

**Issue by weidongguo** [rowyio/rowy#409]
**Is your feature request related to a problem? Please describe.**
In Firetable CMS, JSON field is used to realize what it's called map in Firestore.
Editing the JSON field is a nightmare as we need to repeat the same clicks (+) to set up the structure of the map for every new row

**Describe the solution you'd like**
(1). Can we make the JSON field's structure to be inheritable by new rows? 
(2). If (1) can't be done in the near future, can we allow the JSON field to be able to accept a paste (ctrl + v) into the entire "root" structure. Currently, it can only accept a paste on a subfield when you edit it.
(3) In the long term, have we considered making the JSON editable like a table/collection?

All 3 of them are considered solutions to me.
(3) is being the ideal, (1) is also appreciated, and (2) is like the immediate hack.

**Describe alternatives you've considered**
The alternative is to use a subcollection to implement what I want to realize with a map/JSON. However, every document read in the subcollection is charged, which could have been avoided if they it was a map (JSON) to begin with

e.g.
```
// Document A
{
  field1: value1,
  field2: {
    subfield2_1: "a"
    subfield2_2: "b"
  }
}
```

e.g.
```
// Document B
{
  field1: value1,
}
subcollection_for_field2: {
  document_for_subfield2_1: { 
      value: "a"
  }
  document_for_subfield2_2: { 
      value: "b"
  }
}
```
If the document looks like Document A, which uses map for field2,  it's considered **one document read** to get all of its content
if the document looks like Document B, which uses subcollection for field2, we need to do **three document reads** to get all of its content

**Comment by shamsmosowi** [comment]
have you tried using the default value configuration feature? it can be used to set an initial value for fields such as json when a new row is added

you can find it in the column settings in the dropdown menu

![image](https://user-images.githubusercontent.com/13803906/113571565-f749d980-9659-11eb-974d-3b5512434d18.png)

**Comment by weidongguo** [comment]
Thanks for the suggestion. It certainly helps.

That being said, have we considered making a less-technical / more user-friendly GUI for editing Map?

**Comment by shamsmosowi** [comment]
Yes, I think that would be pretty useful, definitely open to a pull request!
We have some useful docs on field types [here]( https://github.com/AntlerVC/firetable/wiki/Extending-Firetable:-Adding-a-Field-Type)

**Comment by shamsmosowi** [comment]
you can also make individual map fields more user-friendly by adding them as their own columns
eg:
![image](https://user-images.githubusercontent.com/13803906/114002452-39fcf300-98a0-11eb-8bba-8934fa763655.png)
