### ISSUE TITLE
How to add arrays?

### ISSUE THREAD

**Issue by weidongguo** [rowyio/rowy#414]
HOW DO WE ENTER ARRAY IN FIRETABLE?

The closest I can find it's Multi-select, which only takes strings of predefined options. It hints me that the user can enter custom values, but so far, I DON'T how to turn that option on.

How about array of integers?

Alternatively, I try JSON, but it doesn't seem like to allow array at the top level even when I turn on "Set as an Array" IN THE COLUMN

**Comment by grind-t** [comment]
I have the same problem, JSON "Set as an array" option doesn't change anything. How can I make the "root" property an array?

**Comment by shamsmosowi** [comment]
Yes, It looks like set as an array config in the json field is broken , will be fix in the next release this week 🤞

**Comment by shamsmosowi** [comment]
fixed in v2
