### ISSUE TITLE
CSV upload no longer working after update

### ISSUE THREAD

**Issue by bmarkides** [rowyio/rowy#415]
**Describe the bug**
I cannot upload a CSV file after upgrading to the latest version of Firetable.

**To Reproduce**
1. Go to collection table
2. Click on 'import CSV'
3. Either drag file or navigate using file explorer after clicking on CSV field
4. See that it CSV upload is not possible

**Expected behavior**
'Continue' button becomes clickable and CSV is uploaded after clicking 'continue'

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Error experienced on Firefox and Chrome
 - Version 1.3.3

**Additional context**
Thanks, guys!

**Comment by shamsmosowi** [comment]
Just to confirm, you're not reaching this state?
![image](https://user-images.githubusercontent.com/13803906/116963366-00c37180-acec-11eb-9e8f-002aeb373322.png)
