### ISSUE TITLE
Export to csv fails on date field when data filters or sorting is on

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#425]
**Describe the bug**
When trying to export to csv from a table with a date field, if there is a filter on the data or if sorting is done on the date field, then export does not work

**To Reproduce**
1. Go to a table with a date and checkbox fields
2. Click on filter for checkbox field and turn it ON
3. Export data to csv with the date field in the list
![image](https://user-images.githubusercontent.com/307298/117595833-32718800-b185-11eb-864f-f07169c92fda.png)

**Desktop (please complete the following information):**
MacOS on chrome

**Comment by shamsmosowi** [comment]
@harinij is this still broken?

**Comment by harinij** [comment]
Closing issue as it is resolved in recent releases.
