### ISSUE TITLE
Extract JSON value in separate column

### ISSUE THREAD

**Issue by rusakovic** [rowyio/rowy#464]
**Is your feature request related to a problem? Please describe.**
The problem, that we need some specific value in JSON object, but not full information.
For example, for EXIF, we want to see only ISO column, no more
![image](https://user-images.githubusercontent.com/17801144/123526393-ded8e080-d6d7-11eb-8b3a-275a356650f6.png)

**Describe the solution you'd like**
Posibility to add path of JSON object to specific value to extract. `document/exif['iso']`

If it's already possible to do. Sorry for that. Tried to read the full docs.

**Comment by bofeiw** [comment]
You might want to try adding a new column with type derivative. Try the rc branch, it has more helpful info when when you use it.

**Comment by harinij** [comment]
@rusakovic This is now possible. All you have to do is create another column with the column type you want and make the column's Field Key to be jsonfieldname.field value i.e. in your example: exif.iso

See the screenshot below. We also have released a brand new version with tons of other features that you can try out using this easy deploy link to migrate to the new version. Try it out on your existing Firebase project https://rowy.app/deploy
![Screen Shot 2021-09-28 at 4 53 46 pm](https://user-images.githubusercontent.com/307298/135037917-87831333-aa37-4cd4-ac30-3fdab98a9646.png)
