### ISSUE TITLE
Support Firebase geolocation data type

### ISSUE THREAD

**Issue by bofeiw** [rowyio/rowy#481]
### Discussed in https://github.com/FiretableProject/firetable/discussions/479

<div type='discussions-op-text'>

<sup>Originally posted by **hariprasadms** July 14, 2021</sup>
Hi, I am looking to store geolocation details. Looks like there is no data type yet available in firetable as of now. Please suggest how to do this.</div>

**Comment by harinij** [comment]
moved to #535
