### ISSUE TITLE
Bug: [Select field] Column names to allow for nested Objects fieldtype

### ISSUE THREAD

**Issue by n-sviridenko** [rowyio/rowy#497]
I was unable to reopen another issue (https://github.com/FiretableProject/firetable/issues/161#issuecomment-897567508), so I'm opening a new one.

**Comment by murat0** [comment]
I have been experiencing the same thing. When I try and add a nested field with one of the pre-defined types (using "parent.child" notation in field key) I get duplicate entries in Firestore.

**Comment by notsidney** [comment]
Hi, this is fixed as of [v2.0.0](https://github.com/rowyio/rowy/releases/v2.0.0)

You can migrate the latest version of Rowy by using this easy deploy link on your Firestore project: [rowy.app/deploy](rowy.app/deploy). Try it out and we would love to get your feedback [on Discord](https://discord.gg/B8yAD5PDX4) 🙏
