### ISSUE TITLE
Missing Node error on Ubuntu, even when node is installed

### ISSUE THREAD

**Issue by shreyas-jadhav** [rowyio/rowy#503]
**Describe the bug**
I'm getting the following error of missing node. But clearly my system has node installed. Not sure why it's failing to detect.
```
Error: Your system is missing node
Please install node, then re-run firetable init
    at /usr/local/share/.config/yarn/global/node_modules/firetable/src/index.js:30:13
    at Array.forEach (<anonymous>)
    at systemHealthCheck (/usr/local/share/.config/yarn/global/node_modules/firetable/src/index.js:28:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/firetable/src/index.js:108:7)

```
**To Reproduce**
1. `sudo firetable init ./truffll-firestore` on Lubuntu
2. See error

**Expected behavior**
Should init without giving node error

**Screenshots**
![image](https://user-images.githubusercontent.com/73429007/132286051-928be500-eea8-47b5-85a1-42abf99125c6.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/73429007/132286225-14bd9d10-1faf-4942-856d-d8ee5c866c59.png)

**Comment by harinij** [comment]
Hi @shreyas-jadhav we have retired the CLI command and moved towards this quick deploy link to get you set up fast and easily. Give it try here: [1-click deploy](https://rowy.app/deploy)
