### ISSUE TITLE
Reorder items in Image and File fields

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#508]
**Is your feature request related to a problem? Please describe.**
Currently the Images and FIle fields display the content in the order in which the documents were created. 
<img width="340" alt="Screen Shot 2021-09-29 at 12 34 43 am" src="https://user-images.githubusercontent.com/307298/135108543-943f54cd-54a5-4ad5-9ca5-beba95928da0.png">

**Describe the solution you'd like**
The images and files in the columns should be draggable and re-order compatible.

**Comment by ashutosh887** [comment]
Hey @notsidney @harinij 
Is this Issue resolved?
I would like to work on this 😄

**Comment by saravanan-inc** [comment]
Hi @harinij I would like to work on this issue ✌️

**Comment by saravanan-inc** [comment]
Hi  just need help on this issue, in this issue I just implemented the the UI functionality to drag and drop the image but I don't know how to implement the backend functionality such as should the uploaded file is updated or the URL should be updated, and is there a similar functionality exists, you any additional details required just ping me. Thanks for your time.

**Comment by harinij** [comment]
I believe this should just be a UI-level functionality and would not need any changes or updates to the URL of the file/image.  @shamsmosowi can add additional inputs as needed.

**Comment by saravanan-inc** [comment]
> I believe this should just be a UI-level functionality and would not need any changes or updates to the URL of the file/image.  @shamsmosowi can add additional inputs as needed.

Great, just tested by updating the value is the Atom, it does the work. Thanks for the clarification ✌

**Comment by saravanan-inc** [comment]
Hi @harinij managed to merged the pull request, so this issue can be closed. Have a great day.

**Comment by harinij** [comment]
Hi @saravanan-inc thanks for your contribution 🎉 Closing this issue now.
