### ISSUE TITLE
Improve the json field editor on the side bar

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#509]
**Is your feature request related to a problem? Please describe.**
Currently, for the JSON column field, the editing experience in the side drawer on the right is not great. Users have to click on the field value, make the change and then press the save button.
<img width="499" alt="Screen Shot 2021-09-28 at 10 49 17 pm" src="https://user-images.githubusercontent.com/307298/135095933-a31ff294-3ff8-4e1b-9906-795cf3d7c040.png">
<img width="479" alt="Screen Shot 2021-09-28 at 10 49 06 pm" src="https://user-images.githubusercontent.com/307298/135095940-85aa9128-1787-4119-8903-869a66b9492a.png">

**Describe the solution you'd like**
Needs a better UI for building JSON visually ability to click + and then key-value pairs in tree formation

**Comment by harinij** [comment]
**Is your feature request related to a problem? Please describe.**
Currently, for the JSON column field, the editing experience in the side drawer on the right is not great. Users have to click on the field value, make the change and then press the save button. 

<img width="479" alt="Screen Shot 2021-09-28 at 10 49 06 pm" src="https://user-images.githubusercontent.com/307298/135090216-4e1bc671-6501-4a27-b202-e023347c43ca.png">
<img width="499" alt="Screen Shot 2021-09-28 at 10 49 17 pm" src="https://user-images.githubusercontent.com/307298/135090233-218a11bf-0e84-49ab-bb55-47786b717f0f.png">

**Describe the solution you'd like**
Needs a better UI for building JSON visually ability to click + and then key-value pairs in tree formation

**Comment by notsidney** [comment]
Released in v2.2
