### ISSUE TITLE
Rating field - Add customization options

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#513]
**Is your feature request related to a problem? Please describe.**
Currently, the "Rating" field does not have customization.
<img width="668" alt="Screen Shot 2021-09-29 at 8 07 29 pm" src="https://user-images.githubusercontent.com/307298/135248713-a2a90437-8447-454f-9923-59fe3ad49cb5.png">

![image](https://user-images.githubusercontent.com/47289133/190283845-fb53c9b5-8907-407e-9e31-b58aef2ab02a.png)

**Describe the solution you'd like**
Allow icon/emoji picker customization in the rating field setting
- Currently the default option is star icon, allow for emoji picker option (See sample emoji picker used in the customization step of the "Action" field type)
![Screen Shot 2022-02-17 at 10 22 53 am](https://user-images.githubusercontent.com/307298/154374477-6ebef084-7a35-410f-9891-b62f9eeb198a.png)

Rating field code location: https://github.com/rowyio/rowy/tree/develop/src/components/fields/Rating

**Comment by harinij** [comment]
Done @alceil 👍

**Comment by alceil** [comment]
Thanks @harinij

**Comment by mshamsrainey** [comment]
I'll be working on this issue as part of GHC's Open Source Day :-) @harinij

**Comment by harinij** [comment]
Has been merged into dev with a recent release
