### ISSUE TITLE
ROWY-135: Select and Multiselect Fields need color selection for fields

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#514]
**Is your feature request related to a problem? Please describe.**
Currently "Select" and "Multiselect" fields do not have the ability to add color to the option chips being. Only values such as "Yes" "No" "Maybe" are hard coded to be Green, Red and Yellow.
<img width="192" alt="Screen Shot 2021-09-29 at 8 11 04 pm" src="https://user-images.githubusercontent.com/307298/135249524-54a0bdc0-6ecf-4614-b13b-25c939a93be6.png">

**Describe the solution you'd like**
1) Add option to select color for `select` and `multi-select` fields. Here is a sample design.
![multiselect](https://user-images.githubusercontent.com/307298/210921452-86fe90c6-2156-4073-892c-c1e761b1a2c9.png)
2) The default option can be as it is of gray. 
3) Ensure the color being picked is from a list to avoid contrast issue with the text on the chip. 
<img width="346" alt="Screen Shot 2023-01-06 at 1 22 47 pm" src="https://user-images.githubusercontent.com/307298/210921465-9a5edc59-f72b-44a3-a664-a16ccbe91dab.png">

**Comment by devsgnr** [comment]
Hey @harinij - I'd like to work on this.

**Comment by harinij** [comment]
Has been released
