### ISSUE TITLE
Allow reordering of Select and Multiselect field options

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#515]
**Is your feature request related to a problem? Please describe.**
Currently the options listing of Select and Multiselect fields is not reorderable.
<img width="938" alt="Screen Shot 2021-09-29 at 9 12 44 pm" src="https://user-images.githubusercontent.com/307298/135257639-01829e29-80a1-47b5-8b51-f33caaa5697f.png">
<img width="959" alt="Screen Shot 2021-09-29 at 9 12 34 pm" src="https://user-images.githubusercontent.com/307298/135257655-6d8368c8-489b-4a2b-9a9d-ff289f1da26c.png">

**Describe the solution you'd like**
Add the standard drag and reorder feature for the options list of select and multiselect fields

**Comment by saravanan-inc** [comment]
@harinij I am working on this

**Comment by harinij** [comment]
Thanks @saravanan-inc, have assigned it to you 👍

**Comment by harinij** [comment]
@saravanan-inc any progress on this or need input? Unassigning for now as per contribution guidelines. In case you are still working on it, do let us know and you can join us on [Discord](https://www.rowy.io/discord) for any discussion.

**Comment by saravanan-inc** [comment]
https://github.com/rowyio/rowy/pull/1012 created a PR and its waiting for checking

**Comment by harinij** [comment]
This has been merged. Thanks @saravanan-inc for your contribution 🙌🎉
