### ISSUE TITLE
Toggle field - Add customization options

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#517]
**Is your feature request related to a problem? Please describe.**
Currently, the "Toggle" field doesn't have customization to change the color from green to anything else

**Describe the solution you'd like**
Allow in the UI option for users to add color using the color pick modal similar to what is used in the percentage field
![Screenshot 2023-04-20 at 7 07 44 pm](https://user-images.githubusercontent.com/307298/233317767-90a4131d-39cd-421f-a749-2de92f309fa5.png)

**Comment by yasinbordbar** [comment]
Please assign me to do this.

**Comment by ChinazoOnwukaike** [comment]
Can this be assigned to me please?

**Comment by harinij** [comment]
@ChinazoOnwukaike please let us know if you are still working on this or if you need any inputs. Unassigning for now.

**Comment by RajGM** [comment]
Hi @harinij and @notsidney 
The toggle field doesn't have color customization in the column config.

**Comment by RajGM** [comment]
Hi @harinij 
I am working on this: https://github.com/rowyio/rowy/commit/ef4fa7d4818d118f9be304033847096904d9217c

Color pick modal is added.
Remaining: Coloring of the whole field based on true/false;
![ColorModal](https://user-images.githubusercontent.com/16620150/233811318-42eec3ff-7c09-4f68-94f0-33d16177ee21.jpg)

**Comment by RajGM** [comment]
Hi @harinij 

`Is your feature request related to a problem? Please describe.
Currently, the "Toggle" field doesn't have customization to change the color from green to anything else`

Does that means we are only looking to change the color or toggle button instead of whole cell?

**Comment by RajGM** [comment]
![Switch](https://user-images.githubusercontent.com/16620150/233948937-3a2e6ebe-4c47-4931-ac72-5e74e2ff51af.jpg)

**Comment by RajGM** [comment]
Due to the defined type in material UI, we are supposed to pass only: 

(property) SwitchProps.color?: OverridableStringUnion<"primary" | "secondary" | "error" | "info" | "success" | "warning" | "default", SwitchPropsColorOverrides> | undefined

**Comment by RajGM** [comment]
Hi @shamsmosowi
I am trying to change the color but it override the whole thing.

const theme = useTheme();
  const { colors } = (column as any).config;
  const percentage = typeof value === "number" ? value : 0;
  const finalColor = resultBoolColorsScale(
    percentage,
    colors,
    theme.palette.background.paper
  ).toHex();
    console.log("finalColor:", finalColor);
  const theme2 = createTheme({
    palette: {
      primary: {
        main: finalColor,
      },
    },
  });
  
  Any references?

**Comment by RajGM** [comment]
Hi @shamsmosowi and @BeeBombshell 

for the src>components>fields>Checkbox>EditorCell.tsx

`  return (
    <FormControlLabel
      control={
          <Switch
            checked={!!value}
            onChange={handleChange}
            disabled={disabled}
            tabIndex={tabIndex}
            size="small"
            sx={{
              
              
             

            }}
          />
      }
      label={column.name as string}
      labelPlacement="start"
      sx={{
        m: 0,
        width: "100%",
        alignItems: "center",

        "& .MuiFormControlLabel-label": {
          font: "inherit",
          letterSpacing: "inherit",
          flexGrow: 1,
          overflowX: "hidden",
          mt: "0 !important",
        },

        "& .MuiSwitch-root": { mr: -0.75 },
      }}
    />
  );`
  
  Color properties are working for toggled off state with sx props but not for toggled On props.
  
  Link to push: https://github.com/RajGM/rowy/commit/09ae503e18754127d73206e32f6197a7055f1ee1

**Comment by RajGM** [comment]
@iamanishroy

**Comment by harinij** [comment]
Hi @RajGM thanks for pointing it out. Looks like this would not be a feasible solution so we are closing the issue.
