### ISSUE TITLE
Slider Field - Add customization option

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#519]
**Is your feature request related to a problem? Please describe.**
Currently, the "Slider" field does have customization to change the color from red for 0% and green for 100% to anything else
<img width="181" alt="Screen Shot 2021-10-01 at 2 24 33 am" src="https://user-images.githubusercontent.com/307298/135494022-679f2c44-b24a-497c-833d-6488e8ace906.png">

**Describe the solution you'd like**
Ability to pick color from starting and ending percentage and mid percentage. And the color for the in between range will be auto calculated. SImilar to the implementation on the percentage fiel.d

**Comment by ashutosh887** [comment]
Hey @htuerker @harinij I would like to contribute! 😃

**Comment by htuerker** [comment]
Hey, @ashutosh887! Great to hear that! Please, do not hesitate to reach out to me for anything you'd like to ask.

**Comment by ashutosh887** [comment]
How do I set it up locally on my system for Development purposes? @htuerker

**Comment by harinij** [comment]
@ashutosh887 you can follow the instructions for manual install [here](https://docs.rowy.io/setup/install#option-2-manual-install)

**Comment by harinij** [comment]
Hi @ashutosh887 removing for now due to lack of activity.

**Comment by ashutosh887** [comment]
I would like to work on this again
Actually couldn't get help from the community regarding some of my doubts
@harinij @htuerker

**Comment by harinij** [comment]
Hi @ashutosh887 I have reassigned for now. In case of any questions, you can ask on the #contribution channel on Rowy Discord rowy.io/discord

**Comment by ashutosh887** [comment]
Thanks @harinij

**Comment by mnmt7** [comment]
@ashutosh887, are you still working on this? If not, @harinij, can I have the issue assigned to me?

**Comment by ashutosh887** [comment]
Yes @mnmt7 
Creating PR soon
