### ISSUE TITLE
Field Filter UI update - Single and Multi select

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#528]
**Is your feature request related to a problem? Please describe.**
Currently, the single and multi select field's filter does not support "not equal to" option and only supports equal to or matches one of. 
![Screen Shot 2021-10-01 at 4 58 20 pm](https://user-images.githubusercontent.com/307298/135578568-d8c7c890-30ed-4c58-aa37-78cd40aeced5.png)

**Describe the solution you'd like**
Add ability to filter by "Not equal to" option

**Implementation details**
Please find the relevant Firestore documentation: https://cloud.google.com/firestore/docs/query-data/queries#query_operators

**Comment by nandinikaregowdra** [comment]
I would like to work on this issue.
