### ISSUE TITLE
Field Filter UI update - Duration

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#529]
**Is your feature request related to a problem? Please describe.**
Currently, the Filter feature on the top left of the table, does not support duration field.
![Screen Shot 2021-10-01 at 5 16 47 pm](https://user-images.githubusercontent.com/307298/135580609-e8f0eae0-c464-40e7-ae43-bd865fe16f28.png)

**Describe the solution you'd like**
UI needs to support, greater than, less than duration value filtering

**Implementation details**
Please find the relevant file here: [`src/components/fields/Duration/index.tsx`](https://github.com/rowyio/rowy/blob/develop/src/components/fields/Duration/index.tsx)
[`src/components/fields/types.ts`](https://github.com/rowyio/rowy/blob/develop/src/components/fields/types.ts#L69)

**Comment by notsidney** [comment]
This is not possible because we do not store the duration value in the database, so it cannot be filtered by duration.

**Comment by notsidney** [comment]
This is not possible since we don’t store the duration value in the database, only the start and end timestamps.
