### ISSUE TITLE
Update reload screen copy

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#530]
**Is your feature request related to a problem? Please describe.**
Currently, when there is an update or new version of the project, the following screen is displayed that which is not ideal experience with a "Loading chunk 72 error". This error is only when a new version is available and the users should refresh the screen. This is not a real error.
![Screen Shot 2021-10-01 at 12 38 43 pm](https://user-images.githubusercontent.com/307298/135585122-33853667-cb92-4b1c-9d27-5c147316cae2.png)

**Describe the solution you'd like**
Update the copy to say "New update available" instead of "Something went wrong" when error is "Loading chunk" error.
Remove the error message below it and instead say "Refresh you screen to get the latest update.

**Implementation details**
Please find the related file: 
[`src/components/ErrorBoundary.tsx`](https://github.com/rowyio/rowy/blob/main/src/components/ErrorBoundary.tsx#L34)

**Comment by notsidney** [comment]
Released in v2.2
