### ISSUE TITLE
Fix the CSS issue of Import CSV screen

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#531]
**Is your feature request related to a problem? Please describe.**
There are a few CSS issues on the Import CSV's second screen as shown below, with alignment and scrollbar that needs to be fixed
![Screen Shot 2021-10-01 at 11 43 54 am](https://user-images.githubusercontent.com/307298/135589182-1a474b9d-fdae-4064-bffe-c332d5e46e74.png)

**Describe the solution you'd like**
Fix CSS issues as highlighted

**Comment by jmutt78** [comment]
I would like to work on this one.

**Comment by jmutt78** [comment]
Is this project participating in Hacktoberfest?

**Comment by harinij** [comment]
@jmutt78 yes, we have added the hacktoberfest label to the project and I have added the accepted label for your PR now. Thanks for contributing :)
