### ISSUE TITLE
Profile personalization option - Name+Profile Photo

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#532]
**Is your feature request related to a problem? Please describe.**
Profile needs name and profile photo personalization options support
![Screen Shot 2021-10-01 at 6 28 14 pm](https://user-images.githubusercontent.com/307298/135589603-e5c0058a-6a17-4975-a20c-fbfc6b643cac.png)

**Comment by nalin-singh** [comment]
Hey I would like to work on this, do you mean you want to add an edit option for the profile photo and name even after it's fetched from google itself?

**Comment by notsidney** [comment]
Yep, that’s the idea! It would be stored in the user settings document. You can find the component for this in [src/components/Settings/UserSettings/Account.tsx](../blob/main/src/components/Settings/UserSettings/Account.tsx)

**Comment by harinij** [comment]
@nalin-singh Let us know if you would be submitting a PR for this? if not will be opening up this issue for other contributors.

**Comment by RajGM** [comment]
Hi @notsidney 
Where is the user settings document found?
Is, it being fetched from firebase?
Are we supposed to upload image to gcp to user's account and then fetch it or save it on Rowy's firestore?

**Comment by harinij** [comment]
Hi @RajGM we recently refractored the user management and user profile to be fully managed service. So I am going to close this issue at this moment.
