### ISSUE TITLE
Add Geolocation Field

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#535]
**Is your feature request related to a problem? Please describe.**
Currently we do not support geolocation field which is supported by Firebase.
![Screen Shot 2021-10-01 at 11 30 59 am](https://user-images.githubusercontent.com/307298/135591245-2f3ba0f3-2ce4-40b8-a519-1fb08e1eb1ae.png)

**Describe the solution you'd like**
Add support for it, ideally, the UI for inputting the geolocation should support a map UI as well. Take a look at [this doc](https://docs.rowy.io/field-types/add) for how to add new fields.

**Comment by IngridWong0715** [comment]
I'll be tackling this for OSD day

**Comment by IngridWong0715** [comment]
Firebase documentation is recommending against adding the geographical point data type due to limited querying capabilities. It instead recommends storing geolocation with two separate numeric fields for longitude and latitude. Should I still go ahead and add this data type?
