### ISSUE TITLE
Slider Field update - Combine 2 steps of field setup with "Next" button

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#541]
**Is your feature request related to a problem? Please describe.**
Slider fields has two-step in their setup process and their setup is not complete until both steps are completed. The UI needs to be updated to reflect the same i.e after completion of step 1 say "next" to take to the settings of the field before it is added. (See derivatives field for example). 

Slider should not be setup until the two steps of the config are complete. Suggested solution is when a new column is added the "Next" button for the following two step fields should be "Next" to take to the second screen of the "column setting" instead of current "Add" button.

**Comment by yashodha03** [comment]
I would like to work on this issue.
