### ISSUE TITLE
Copy/Cut/Paste feature in table view

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#544]
Allow for field cells to be copied/cut or pasted with keyboard shortcuts to other fields.

Ensure there is logic applied when one field is copied to another field to check compatibility.
i.e.  
- copy json field -> past to long text - stringify the data
- copying fields like rating should copy the value of the field
- don't allow incompatible fields

Rowy uses [react-data-grid](https://github.com/adazzle/react-data-grid) checkout the examples there for the basic implementation of copy/paste feature.

**Comment by gibsonliketheguitar** [comment]
#598 related to hotkey
