### ISSUE TITLE
Update the Duration Field - Input UI

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#545]
**Is your feature request related to a problem? Please describe.**
Currently, the Duration Field is alpha feature and not editable.

![Screen Shot 2021-10-02 at 1 58 57 am](https://user-images.githubusercontent.com/307298/135651517-0f7ca0f4-5b8d-4bc9-80c2-df2115cc77fa.png)

**Describe the solution you'd like**
Add UI for adding duration field with start and end date time picker and calculated duration is stored in the field

**Comment by ParimalaKonduru** [comment]
I would like to work on this.
