### ISSUE TITLE
Status field - show dropdown in the table cell & side drawer

### ISSUE THREAD

**Issue by notsidney** [rowyio/rowy#546]
**Is your feature request related to a problem? Please describe.**
Currently the Status field is not editable in either the table cell or side drawer field.
![image](https://user-images.githubusercontent.com/27017118/135653605-bbace4fb-0efc-4060-98d7-1f8d6c469b58.png)

**Describe the solution you'd like**
Add the ability to edit the field value using a dropdown, like the single select field

**Comment by serenal96** [comment]
Would like to work on this
