### ISSUE TITLE
404 After following the "Run on Google Cloud" button

### ISSUE THREAD

**Issue by Yakito** [rowyio/rowy#554]
**Describe the bug**
After following the Run on Google Cloud button I am presented with the following information
[ ✓ ] Your application is now live here:
        https://rowy-run-xxxxxxxxxx-uc.a.run.app 

Once I follow the link I am taken here https://rowy.app/404

**To Reproduce**
1. Click the "Run on Google Cloud" button
2. Click on the resulting link

**Expected behavior**
I should be able to setup the application

On this link https://docs.rowy.io/setup/install it looks like I should be presented with a message and a link I should follow to complete the installation
![image](https://user-images.githubusercontent.com/992405/136125921-83ca367e-3180-47c5-8a1d-ae4b1a1b08c3.png)

but my shell looks like this
![image](https://user-images.githubusercontent.com/992405/136126018-d2f153ca-f14b-4192-b081-7382414dddf9.png)

Any ideas will be appreciated!
Thanks!

**Comment by shamsmosowi** [comment]
the green box, only shows up on the first install of rowy run,
clicking the live cloud run link also redirects to the setup page
