### ISSUE TITLE
UI Drawer crashes if imported column is / row 'cell' is Array of Document References

### ISSUE THREAD

**Issue by joshensongric** [rowyio/rowy#565]
**Describe the bug**
//A clear and concise description of what the bug is.

**IF** a firestore document contains an array of firestore document refernence sub fields within that array

**THEN** the Rowy UI drawer crashes / refuses to load / display any data for tha particular document / Row of the Table.

**To Reproduce**
1. Create 2 firestore collections (colA & colB)
2. Create one new firestore document in collection A (doc1A) and 2 new documents in Collection B (doc2B & doc3B - use AutoID)
3. In doc1A (within collection A) add a new field (Type: Array / FieldName: ListOfDocReferences)
4. add 2 or more fields to the array:
- sub-Field1 (Type: (document) Reference // Value: PathToDoc2B)  -- e.g. "/collection_b/doc2B_idAABBCCDDEEFFGG"
- sub-Field2 (Type: (document) Reference // Value: PathToDoc2C) -- e.g. "/collection_b/doc2C_idHHGGIIKKLLMMNNOO"

3. Add new table to Rowy (Type: Primary Collection // Link: CollectionA)
4. Import all fields (ListOfDocReferences will default to Type: Json)
5. Click on the row for doc1A in new Rowy Table
6. See error message

**Expected behavior**
Rowy UI Drawer will appear showing expanded view of details for that row / firestore document

BUT --> Error, no data / drawer UI loads for doc1A 

NOTE --> This seems to e the same error that previously was reported and fixed, which was focused on a single Document Reference field in a document, but produced the same Drawer UI crash in Rowy.

**Screenshots**
![Screenshot 2021-10-18 06 19 33](https://user-images.githubusercontent.com/71047441/137673324-2ce9b49c-67c1-4f15-838d-97705ad574ba.png)
![Screenshot 2021-10-18 06 19 18](https://user-images.githubusercontent.com/71047441/137673325-a9477f07-3372-4929-ac4d-b3f2a0bb16ef.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - ChromeOS
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - Version 94.0.4606.97 (Official Build) beta (64-bit)

**Additional context**

NOTE --> This seems to e the same error that previously was reported and fixed, which was focused on a single Document Reference field in a document, but produced the same Drawer UI crash in Rowy.

**Comment by notsidney** [comment]
Released in v2.2
