### ISSUE TITLE
Support Connect Table without Algolia

### ISSUE THREAD

**Issue by achataignier** [rowyio/rowy#575]
Connect Table is a great and required feature for most applications. It would be very useful to be able using it without the (commercial and not-free) Algolia index. This should be possible by using Firestore indexes instead, which are almost-free.

Make the use of Algolia mandatory for the Connect Table feature is a blocker for using Rowy in projects requiring low-cost deployments.

**Comment by shamsmosowi** [comment]
Hi @achataignier, this definitely something we will need to look into in the future, PRs are also welcome!
For now we do have a [Meilisearch](https://www.meilisearch.com/) extension and you can use [connect service](https://docs.rowy.io/field-types/connect-service) column to make an endpoint accessible similar to how connect table works, It is a bit more complicated than using connect table though as you'll have self host a Meilisearch instance yourself.

**Comment by harinij** [comment]
New connector field supports this. Documentation here: https://docs.rowy.io/field-types/connector
