### ISSUE TITLE
Unable to publish the build folder on to Github pages

### ISSUE THREAD

**Issue by Rohitbels** [rowyio/rowy#576]
**Describe the bug**
Unable to publish the build folder on to Github pages.
I have also added the URL to google auth under Firebase Auth.

in package.json I have entry
  **"homepage": "https://rohitbels.github.io/rowy/",**

**To Reproduce**
1. Add "gh-pages"
2. Add the deploy script
3. npm run deploy

**Expected behavior**
Login screen should appear

**Screenshots**
![Screenshot 2021-11-10 at 11 18 30 AM](https://user-images.githubusercontent.com/4401718/141057209-6f038d24-b123-4ae4-a47d-ec96d0db4203.png)

**Comment by shamsmosowi** [comment]
hi @Rohitbels, You need a hosting service that serve the rowy app on the root `/` not `/rowy/`  or any thing else, im not sure if github supports that, but you can use firebase hosting, netlify or vercel etc

**Comment by notsidney** [comment]
If you want to use GitHub Pages, you’ll need to make modifications to the Create React App config, like how it’s outlined in the answer here: https://stackoverflow.com/questions/49429906/how-should-i-configure-create-react-app-to-serve-app-from-subdirectory
