### ISSUE TITLE
Can't create read only tables

### ISSUE THREAD

**Issue by eneesolutions** [rowyio/rowy#577]
**Describe the bug**
I have created a table to view users and I want to prevent any writing or adding rows/columns or deleting.

I have set up the security rules with write set to false for my USER role, this works.

However the UI does not update, so it looks like the logged in USER can make changes to the table, which makes for a bad experience.

Is there some way to set a table as read-only for some roles?

**Comment by notsidney** [comment]
Hi, you can set all the columns in the read-only table to be Locked in the column menu. This prevents the user from being able to edit the data in the UI, preventing the issue you said where it looks like the user can edit data but isn’t reflected on Firestore because of security rules

**Comment by eneesolutions** [comment]
Locking the columns did improve the situation slightly, but my USER role can still duplicate rows, try to delete and add columns etc.

I've attached a screenshot of the areas I wouldn't want the user to see and confuse them:

<img width="980" alt="Screen Shot 2021-11-12 at 12 02 59" src="https://user-images.githubusercontent.com/63626327/141393607-79292416-ff1c-4b9a-bfbf-6a0a74e1cd63.png">

**Comment by notsidney** [comment]
Thanks for this, we’ll definitely look into adding read-only tables to make this simpler
