### ISSUE TITLE
Enable non-admins managing select option values

### ISSUE THREAD

**Issue by n-sviridenko** [rowyio/rowy#580]
**Is your feature request related to a problem? Please describe.**

We don't want giving our staff ADMIN permissions, but they need to be able to add new option values without distracting us every time.

**Describe the solution you'd like**

Everyone authenticated should be able to manage option values. This can be also configured on a field level (e.g. "Who can manage option values: Everyone | Only admins").

**Describe alternatives you've considered**

See above.

**Comment by shamsmosowi** [comment]
I agree, this would be a very common use case. 
Currently all column configurations go through the client-sdk with firestore rules enforced, and with the current table schema structure it would be too complex if not impossible to create rules that would allow editing rights to the options specifically, without rights to editing all column configurations. 
Potentially it could be implemented by adding an endpoint on Rowy Run, that can manage the custom logic for allowing the desired behaviour.

**Comment by notsidney** [comment]
Hello, we now allow users with the OPS role to configure columns in v2.6.0
