### ISSUE TITLE
Multiple filters support

### ISSUE THREAD

**Issue by n-sviridenko** [rowyio/rowy#582]
**Is your feature request related to a problem? Please describe.**

We need to be able to have multiple filters applied to a view. Indexes have to be created either automatically (via rowyRun) or it should prompt a link to generate them.

**Comment by shamsmosowi** [comment]
I think it should be automatic via rowyRun, since it is doable using the admin-sdk

**Comment by n-sviridenko** [comment]
I'd also clean the index if the filter gets removed (with a prompt ofc).

**Comment by n-sviridenko** [comment]
Hey guys, any updates on this, or at least an approximate timeline? cc @shamsmosowi

**Comment by notsidney** [comment]
Hi @n-sviridenko, looking at our internal timeline, we don’t plan to work on this feature until early next year, maybe February. We’re focusing on improving existing features and removing friction for new users to start using Rowy, and we’re counting this a new feature.

**Comment by gibsonliketheguitar** [comment]
> We need to be able to have multiple filters applied to a view. Indexes have to be created either automatically (via rowyRun) or it should prompt a link to generate them.


@n-sviridenko Hey Nick, I am new to this repo. Can you define "view" in relation to rowy. I will start looking into this! Please and thank you.

**Comment by n-sviridenko** [comment]
@gibsonliketheguitar  View (in airtable's world) is a table (in rowy's world).

**Comment by harinij** [comment]
Task:

Add support for multiple filters as per this [design file](https://www.figma.com/file/EqYCCoU6jpA7I3guxpyfhl/Multiple-filters?type=design&node-id=1%3A2911&t=9WZapQFZo7QvGJU0-1)

Firebase now supports and & or queries.

**Comment by haruncurak** [comment]
Gonna give this a crack! 

/attempt 582

**Comment by ashutosh887** [comment]
@harinij @BeeBombshell  Let me attempt this one if not resolved yet!

**Comment by harinij** [comment]
/tip $25 @mnmt7 thanks for your PR, we have closed it due to conflicts for backward compatibility. 

Latest PR for this issue is #1390 and will be merged soon.
