### ISSUE TITLE
Filters have to be common for all users

### ISSUE THREAD

**Issue by n-sviridenko** [rowyio/rowy#587]
**Is your feature request related to a problem? Please describe.**

Like on Airtable, filters have to be applied on a table level rather than on a user level. I want to configure views in a way so that my team can benefit from the filters I set. I don't want 20 people configuring the same filters again and again.

P.S. I shared this feedback ~2 months ago over email, so you might already have an issue for that.

**Comment by n-sviridenko** [comment]
Hey guys, any updates on this, or at least an approximate timeline? cc @shamsmosowi @notsidney

**Comment by notsidney** [comment]
Hi @n-sviridenko, we’re investigating this as part of our current sprint, but cannot guarantee it will be part of the next release this month as v2.3
