### ISSUE TITLE
Right click menu for cells

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#600]
Add right click menu for table cells with useful features such as..

copy, paste
copy column name, id, ref 

other ideas welcome to discuss

**Comment by gibsonliketheguitar** [comment]
Should we have a global state in Jotai to store the copying of values

**Comment by shamsmosowi** [comment]
hi @gibsonliketheguitar, the copied values should be stored into the clipboard, so users are able to move their data out of rowy.
We should be keeping the same style as the column menu, but no need to include column level functionality included in the column menu already.

**Comment by src200** [comment]
Opened a PR https://github.com/rowyio/rowy/pull/621

**Comment by gibsonliketheguitar** [comment]
> Opened a PR #621

Was working on this to  #622. 
In addition, @src200 I notice you wrapped the Row with the ContextMenu.

The potential problem is the necessary duplication on all the <Row />
My implementation followed the ColumnMenu Code, and used  a CellMenuRef to handle the conditional rendering of the ContextMenu


@shamsmosowi  @src200 Let's figure out who will be taking this ticket
