### ISSUE TITLE
Cannot send email via SendGrid due to secret manager error

### ISSUE THREAD

**Issue by AndrewGable** [rowyio/rowy#629]
**Describe the bug**
I am attempting to send emails via the sendgrid extension, however, it is failing with the following error:

```
[{"status":"rejected","reason":{"code":7,"details":"Permission 'secretmanager.versions.access' denied for resource 'projects/<project-id>/secrets/sendgrid/versions/latest' (or it may not exist).","metadata":{"grpc-server-stats-bin":[{"type":"Buffer","data":[0,0,243,218,139,4,0,0,0,0]}]},"note":"Exception occurred in retry method that was not classified as transient"}},{"status":"fulfilled","value":[]}] 
```

**To Reproduce**
1. Create a new secret in the secrets-manager UI named `sendgrid`
2. Go to extensions and create a new send grid extension
3. Trigger it via `create`
4. I get the error above 💥 

**Expected behavior**
I would expect the extension to be able to find the secret correctly

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 97

**Additional context**
My secret's `Resource ID` appears to be created under the **Project number** and not the **Project ID** which it seems like the code is referencing.

**Comment by shamsmosowi** [comment]
Just to confirm, have you added secret accessor role to the default service account used by the cloud function?
I've just added some basic docs [here](https://github.com/rowyio/docs/blob/main/docs/extensions/extensions.md#-secret-mananger-access) 
let me know if that doesnt help

**Comment by AndrewGable** [comment]
I gave both the `Rowy Backend service Account` and the `firebase-adminsdk` the roles, but is there a different account that I should grant that role as well? I don't see a service account with `projectId@appspot.gserviceaccount.com`


<img width="1153" alt="Screen Shot 2022-01-29 at 3 50 49 PM" src="https://user-images.githubusercontent.com/2838819/151680160-b3cd24e7-21bf-4ee3-a24c-19412d6620f6.png">
 

<img width="1156" alt="Screen Shot 2022-01-29 at 3 51 02 PM" src="https://user-images.githubusercontent.com/2838819/151680159-0082165e-a9eb-40f1-b845-80281391ee84.png">

**Comment by AndrewGable** [comment]
Ok I got it, apologies I am new with IAM! 

I had to:
1. Add `projectID@appspot.gserviceaccount.com` as a new principals
2. Grant it the `Secret Manager Secret Accessor` role

Thanks for the help!
