### ISSUE TITLE
Filter table by Row's ID or Metadata ID

### ISSUE THREAD

**Issue by saenzramiro** [rowyio/rowy#668]
**Is your feature request related to a problem? Please describe.**
In our case, our collection of users have the email address of the user as the document ID. When I create a table, I can add a column using the "Metadata - ID" field type to display that information, but when I want to search for a specific email you cannot do it because it is not a field, I guess.

**Describe the solution you'd like**
Extend the filter options to search by the Metadata - ID / Row's ID.

**Describe alternatives you've considered**
Maybe adding a new field type for "Mapping" other fields. So if I have a field for First Name and other for Last Name, with this field I can join both to have the full name. Of course, this type of field will be only internal/visually and not do any change in Firestore.

Regards.

**Comment by shamsmosowi** [comment]
Hi @saenzramiro, 
The filtering functionality on Rowy uses a firestore query, firestore queries don't handle documentId as query parameter.
for the same reason creating a client side mapping field wouldn't work as it wouldn't be queryable on Firestore.
A solution for you would be to include email as field in the document, you can do that easily using default values
[like this](https://docs.rowy.io/how-to/default-values#example-reference-data), or include it in your code that initially creates the document

**Comment by saenzramiro** [comment]
Thank you for your answer.
Ok, and what about doing something with the URL? Because when I click on a row, is changing the URL to the path of that document in the **rowRef** parameter. A workaround that I found is:

1. Click on a row of another user to have the path of that document in the URL.
2. Change in the URL the email of the user to the user I want to find.
3. After page reload, open the side drawer to see the details of that user.

Maybe in the Filters modal, you can add a "Document filter" that do this.

What do you think?

**Comment by shamsmosowi** [comment]
are you suggesting "document filter" only updates the side drawer, and not the table?

**Comment by saenzramiro** [comment]
Well, it will be great if you can redraw the table showing a single row with document data to have a better experience.

If is not possible, I think having only the drawer is better than nothing. 💪🏼

**Comment by saenzramiro** [comment]
👀

**Comment by saenzramiro** [comment]
Awesome news! Thanks.
