### ISSUE TITLE
[deploy.rowy.app] CORS issues

### ISSUE THREAD

**Issue by bennetfabian** [rowyio/rowy#680]
**Describe the bug**
On https://deploy.rowy.app in Step 2, when trying to select a project, it shows "NetworkError when attempting to fetch resource." on Firefox and "Failed to fetch" on Chrome on the bottom left.
The console output in Chrome:
```
Access to fetch at 'https://deploy-api.rowy.app/firebaseProjects' from origin 'https://deploy.rowy.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Failed to load resource: net::ERR_FAILED
```

**To Reproduce**
1. Login with your Google account on https://deploy.rowy.app
2. Go to Step 2

**Expected behavior**
Projects should show in the dropdown list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Browser: Firefox as well as Google Chrome
 - Version: Firefox 100, Google Chrome 102.0.5005.61

**Additional context**
Sorry if it's not the right place but maybe you can redirect this to the engineers responsible.

**Comment by shamsmosowi** [comment]
Hi @bennetfabian, 
in step 1, did you login with an email that already has projects on GCP & give consent for cloud platform access?
you can [logout](https://deploy.rowy.app/signout) and try again, see if that helps
otherwise please DM me on discord your email, I can look into the issue for you

**Comment by bennetfabian** [comment]
> Hi @bennetfabian, 
> 
> in step 1, did you login with an email that already has projects on GCP & give consent for cloud platform access?
> 
> you can [logout](https://deploy.rowy.app/signout) and try again, see if that helps
> 
> otherwise please DM me on discord your email, I can look into the issue for you 

Yes, I did login with an Google account already having projects on GCP and I did give cloud platform access consent.

Logging out and logging in back again also doesn't help.
Thanks for you offer, I'll message you!
