### ISSUE TITLE
Build logs expand/collapse menu does not collapse completely.

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#693]
**Describe the bug**
When building derivative column function and deploying

**To Reproduce**
1. Create a derivative column (see sample [here](https://demo.rowy.io/table/whatToWatch#columnModal=%7B%22type%22%3A%22config%22%2C%22columnKey%22%3A%22movieId%22%7D) 
2. Deploy the column
3. The build log modal shows up on the left
4. Expand/collapse the modal does not work as expected to collapse fully

Video: 
https://user-images.githubusercontent.com/307298/175227405-dcae3fef-9f04-4130-8304-831d3ebb3edd.mp4

**Expected behavior**
1. It should start with default to collapse fully, instead of expand.
2. Collapse should convert the modal to height of a typical snack bar size with just the build log and progress indicator - instead of the content

**Comment by Ciggzy1312** [comment]
Hey, I can give this a try

**Comment by harinij** [comment]
@Ciggzy1312 Would you be submitting a PR? Let us know if you are still working on it/need any additional info. If not, we will be unassigning it so that others in the community can take a look. Thanks

**Comment by ganeshmani** [comment]
@harinij  @Ciggzy1312 Is this issue fixed, or is anyone working on this issue? If not, I can work on this.

**Comment by Ciggzy1312** [comment]
Sorry, am caught up with a lot
@ganeshmani feel free to go ahead

**Comment by harinij** [comment]
Merged and released
