### ISSUE TITLE
Rowy shows error message if cloud function runs for more than 1 minute

### ISSUE THREAD

**Issue by aritraroy** [rowyio/rowy#698]
**Describe the bug**
If a cloud function runs for more than 60 seconds, Rowy automatically shows an error message "Failed to run action. Check the column settings.".

**To Reproduce**

1. I have an Action button connected with a Firebase Cloud Function. Pressing the button triggers the cloud function.
2. If the cloud function runs for more than 1 minute it shows this error message and the loading indicator in the button also stops - https://share.cleanshot.com/uZBXfk
3. But the cloud function actually continues to run in the background as we have increased the timeout with - "timeoutSeconds: 540"

**Expected behavior**
Even if the cloud function runs for more than 1 minute, there should be no error message shown. It should behave in a similar way as it behaves when the cloud function runs for less than 60 seconds.

**Screenshots**
[Screenshot ](https://share.cleanshot.com/uZBXfk)

**Rowy Run version**
Rowy v2.6.1

**Comment by shamsmosowi** [comment]
Hey @aritraroy ,
It looks like the callable function [here](https://github.com/rowyio/rowy/blob/main/src/components/fields/Action/ActionFab.tsx#L96) expects timeout as an option and defaults to 70 seconds if nothing is provided.

**Comment by aritraroy** [comment]
@shamsmosowi I see. Currently, I am calling the function from Actions settings like this - https://share.cleanshot.com/tsnYfz.

How do you suggest I pass the timeout options here? An example will be helpful for me to try out.

**Comment by shamsmosowi** [comment]
currently there's no setting for it, I think we should just update the default to 540 seconds instead, since thats the maximum  a cloud function could run for. We'll need to test what happens if the cloud function timesout first, to see how that error is handled.

**Comment by aritraroy** [comment]
Yes, changing the default to 540 sounds like a good idea. Please let me know whenever this change is made.

**Comment by aritraroy** [comment]
@shamsmosowi Any update on when this can be expected to be fixed? I am facing this issue almost regularly.

**Comment by notsidney** [comment]
Hi @aritraroy, it looks like it was fixed a while back but we didn’t push the update to rowy.app. I’ve done that now.

**Comment by aritraroy** [comment]
@notsidney Thank you

**Comment by frank-bee** [comment]
@notsidney , there still seems to be a 60000 ms timeout 
see https://github.com/rowyio/rowy/discussions/1441
