### ISSUE TITLE
Import Firestore Reference field using CSV

### ISSUE THREAD

**Issue by notsidney** [rowyio/rowy#707]
### Discussed in https://github.com/rowyio/rowy/discussions/706

<div type='discussions-op-text'>

<sup>Originally posted by **polenvinagre** July 14, 2022</sup>
Hi! Could someone help me. How can I import a reference field to firebase?
I tried use json but it import a array of data.
I tried ref field but it was blank/empty.
I am using a csv file.</div>

**Describe the solution you'd like**
When a CSV contains a Firestore reference as a path to a document, e.g. `collection/document_id`, we should be able to use that as a value for a Reference type column.

**Additional context**
Find the code for importing CSV at [`src/components/TableModals/ImportCsvWizard/ImportCsvWizard.tsx`](../blob/main/src/components/TableModals/ImportCsvWizard/ImportCsvWizard.tsx)

**Comment by harinij** [comment]
Tracked here: https://github.com/rowyio/rowy/issues/704

**Comment by harinij** [comment]
Has been released
