### ISSUE TITLE
Missing Features and issues request

### ISSUE THREAD

**Issue by zakblacki** [rowyio/rowy#711]
Hi, here some ideas to improve rowy :
- We cannot see the document Id (row)  (if user want to create a new row we should be allowed to set the name or id manually not auto generate)
- There is no search feature available (to find some specific data in our collection)
- Also we need feature to upload images to storage and get link from it 
- It's annoying to have to edit Field type (give option for users if they want to change auto or not Urgent)

**Comment by notsidney** [comment]
Discussion #713
