### ISSUE TITLE
Add customization option to long text field

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#718]
**Is your feature request related to a problem? Please describe.**
Currently, short text field supports the following customization, to check for character limit and regex. The long text field does not provide these options. Add these options to long text field as well.

**Short text field config**
![Screen Shot 2022-07-20 at 12 18 48 pm](https://user-images.githubusercontent.com/307298/179881838-78eed77d-d85a-49f6-ae10-b0e0c49c6c10.png)

**Long text field config**
![Screen Shot 2022-07-20 at 12 19 45 pm](https://user-images.githubusercontent.com/307298/179881962-0d786b3f-f817-4439-a04f-84a6f910b897.png)

**Comment by RajGM** [comment]
PR: https://github.com/rowyio/rowy/pull/821

**Comment by RajGM** [comment]
Hi @harinij 
I think we should close this issue since PR has been merged.
