### ISSUE TITLE
Problem with some special characters importing CSV file.

### ISSUE THREAD

**Issue by BeeBombshell** [rowyio/rowy#748]
### Discussed in https://github.com/rowyio/rowy/discussions/746

<div type='discussions-op-text'>

<sup>Originally posted by **paconde** August 11, 2022</sup>
Hello, when importing a CSV file, I have problems with some special characters, such as "Ñ" or "º". Is there any solution?
</div>

### Sample Screenshots Depicting the Issue
<img width="509" alt="image" src="https://user-images.githubusercontent.com/53828745/184835227-31b19ef7-0d9a-4044-a5d7-89669dfc1d2a.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/53828745/184835388-49a1a44f-3f8d-41d3-8c99-df6572ecaa47.png">

**Comment by RajGM** [comment]
Hi @BeeBombshell 
I am taking this.

**Comment by RajGM** [comment]
https://github.com/rowyio/rowy/discussions/940
https://www.npmjs.com/package/iconv-lite

**Comment by RajGM** [comment]
Open the issue for other people, @BeeBombshell

**Comment by harinij** [comment]
This issue has been answered [here](https://github.com/rowyio/rowy/discussions/746#discussioncomment-3486074). Closing it now.
