### ISSUE TITLE
Richtext field needs a full screen mode, similar to markdown fieldtype

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#752]
**Is your feature request related to a problem? Please describe.**
Currently, the rich text field is editable only in the side drawer. It can be limiting sometimes especially if you are using it to create long-form blog content. The rich text field type can use a fullscreen mode similar to the markdown field.

**Describe the solution you'd like**
Currently, the markdown field in side drawer has a button to expand it to a full screen mode, as show below.
<img width="485" alt="Screen Shot 2022-08-20 at 11 02 01 am" src="https://user-images.githubusercontent.com/307298/185723439-55de7a01-073c-4b0e-afab-0692e435c653.png">

We need a similar button in the richtext field to be able to expand the view to full screen mode.
<img width="475" alt="Screen Shot 2022-08-20 at 11 02 10 am" src="https://user-images.githubusercontent.com/307298/185723446-38b357e6-96e4-4add-957e-25ea5eb34815.png">

**Comment by RajGM** [comment]
Working on this.

**Comment by harinij** [comment]
@RajGM any update on this? Otherwise we will be opening it up to others.

**Comment by saravanan-inc** [comment]
@harinij is this feature exist in the project or it should be added newly cause the images should, is of for reference or it needs to be created??
![image](https://user-images.githubusercontent.com/59250081/203006026-adb5b508-1db0-43e2-8896-8ac9bac4c1a5.png)

**Comment by saravanan-inc** [comment]
@harinij Working on this

**Comment by RajGM** [comment]
Hi @saravanan-inc 
Make sure to continue the work form here:
https://github.com/RajGM/rowy/commit/b24c57812a3c93ee69772ee05b03bacd5584cbff

**Comment by RajGM** [comment]
In that particular commit, the toggle feature and the rest of the functions are implemented except the container that makes it go full screen.
Just toggle the full-screen function by copying from the markdown field.

**Comment by RajGM** [comment]
Hi @harinij 
Yeah, sure, make it open.

> @RajGM any update on this? Otherwise we will be opening it up to others.

**Comment by saravanan-inc** [comment]
@harinij https://github.com/rowyio/rowy/pulls

**Comment by HeadStarterz** [comment]
I also urgently need this function. We wanted to use Rowy for a publication process where we need to format long texts. For this we need a fullscreen mode, otherwise the field is too small. When can we expect implementation here?

**Comment by RajGM** [comment]
Hi @HeadStarterz 
PR has been made for this feature.
Most probably it will be release in the next cycle or prior to that.

**Comment by HeadStarterz** [comment]
Hi @RajGM. Thank you for your reply. Great news!

**Comment by saravanan-inc** [comment]
@harinij can you close the issue its merged

**Comment by harinij** [comment]
Merged into develop
