### ISSUE TITLE
Pass the number from the column to the array

### ISSUE THREAD

**Issue by organicnz** [rowyio/rowy#775]
Hi folks,

Thank you for the lovely product :)
Is it possible to pass the number from the column to the array by any chance? :)

Thank you :)

<img width="1440" alt="Screen Shot 2022-08-29 at 7 00 52 PM" src="https://user-images.githubusercontent.com/4765090/187248192-72896ca7-cc1b-4dca-ac43-a03de14de011.png">

**Comment by shamsmosowi** [comment]
Hi @organicnz,
not sure what exactly what you want to achieve, if you mean to use the number column to select an element in the array. The syntax would be something similar to this `row.dictionaryApi.records[row.number].fields.Name`
feel free to elaborate on your goal, we can try and help

**Comment by organicnz** [comment]
Hi @shamsmosowi,
Ooh, sorry that wasn't quite clear, mate :)
Geez, I've been using $ sign for that purpose. Thank you very much for your great help :)
