### ISSUE TITLE
Pop-up that shows document details is not responding. Page becomes unresponsive and remains until hard refresh. Browser eventually kills the tab.

### ISSUE THREAD

**Issue by yuriibabii** [rowyio/rowy#782]
**Describe the bug**
Recently I changed a structure of a collection, and I think the reason to this error is IDocumentReference. On Firebase website everything is ok. In Rowy cell I see some symbols that are not familiar to me, 
**To Reproduce**
1. Go to 'Collection'
2. Click on 'Row'
3. See freeze

**Expected behavior**
Row with Reference should be displayed without any problems

**Screenshots**
<img width="990" alt="Screenshot 2022-08-31 at 16 22 39" src="https://user-images.githubusercontent.com/12963450/187702345-1281e5cc-05df-4c0a-b42b-7afbdec6d59d.png">

On Firebase the same row looks ok
<img width="570" alt="Screenshot 2022-08-31 at 16 22 55" src="https://user-images.githubusercontent.com/12963450/187702356-4678f5fc-8c64-47fb-90b9-a367d24abfa7.png">

**Rowy Run version**
Rowy v2.6.1

**Comment by notsidney** [comment]
Hi @yuriibabii, we can’t support Firestore refs in JSON fields, because the Firestore ref object can’t be serialized to JSON and we can’t convert JSON back to a Firestore ref object to be stored in the database.
