### ISSUE TITLE
Email field: Validation regex option

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#799]
**Is your feature request related to a problem? Please describe.**
Validation and regex options are currently available for only fields like short text and long text. Whereas the email field does not have a default validation option/customization.

If you go to the email field config [here](https://demo.rowy.io/table/allFieldTypes#page=1&columnModal=%7B%22type%22%3A%22config%22%2C%22columnKey%22%3A%22email%22%7D), you will note that validation check option is not available.

**Describe the solution you'd like**
<img src="https://user-images.githubusercontent.com/307298/189788647-6bf395c4-aa73-4317-bb69-8b506fb1d539.png" width="700"/>
To the below email config modal shown above, add the validation regex option as shown below. The validation regex option should have a default value of `[a-z0-9]+@[a-z]+\.[a-z]{2,3}`

<img src="https://user-images.githubusercontent.com/307298/189788656-c8cf2c7a-0fca-47e0-bed1-4b6e550301e5.png" width="700"/>

**Comment by likitarai1** [comment]
@harinij I would like to work on this issue.

**Comment by RajGM** [comment]
Hi @harinij 
I think default value could be: ^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+\.[a-zA-z]{2,3}$

**Comment by RajGM** [comment]
Made a PR: https://github.com/rowyio/rowy/pull/820

**Comment by thinktrans** [comment]
If I may, I would like to request you to not put in the regex as decided. It invariably leaves the Internationalized Email addresses at bay. If possible, keep it as simple as this:
<e-mail local part>@<domain name>
Which can be implemented as 

For <e-mail local part> - Follow the guidelines by the "Universal Acceptance Steering Group" - UASG-026 - https://uasg.tech/download/uasg-028-considerations-for-naming-internationalized-email-mailboxes-en/

For <domain name>, you can follow any domain validation methodology using standard libraries, depending on your programming language. For the recent studies on the subject, follow the document UASG-018A - https://uasg.tech/download/uasg-018a-ua-compliance-of-some-programming-language-libraries-and-frameworks-en/.

**Comment by notsidney** [comment]
Hi @thinktrans, this will be an optional feature that has to be explicitly enabled in column config.

**Comment by ashutosh887** [comment]
I would like to work on this Issue!

**Comment by RajGM** [comment]
Hi @ashutosh887 
I made a PR for the issues and will open a discussion about the errors I am facing.

**Comment by RajGM** [comment]
Hi @notsidney 
Updated PR: https://github.com/rowyio/rowy/pull/820/

**Comment by RajGM** [comment]
Hi @harinij 
This should be closed now.

**Comment by Nike682631** [comment]
I don't think this issue should be open from @RajGM 's comment? Is it resolved?

**Comment by harinij** [comment]
Thanks for pointing out, closing it now.
