### ISSUE TITLE
Editing Array fields of strings

### ISSUE THREAD

**Issue by amiregelz** [rowyio/rowy#807]
**Describe the bug**
I have a field which is an array of text strings.
When trying to edit this field in order to add, modify or delete one of the strings, it opens a Multi-Select box with 0 options.

**Expected behavior**
All I want is to edit the array like text or code or JSON, is that possible?

**Screenshots**
<img width="277" alt="image" src="https://user-images.githubusercontent.com/1956341/189865455-df46f547-eb76-4820-b898-d05099697381.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/1956341/189865510-ee87e202-4933-4085-8036-8f02a083b9b7.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/1956341/189865548-93590284-2ecc-450a-9c2c-33fcf2d6c1f1.png">

**Rowy Run version**
If applicable, share the Rowy Run version from your project settings.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by harinij** [comment]
@amiregelz The new array column now supports this. Documentation here: https://docs.rowy.io/field-types/array-overview#array-field
