### ISSUE TITLE
Support bulk deletion of rows 

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#809]
**Is your feature request related to a problem? Please describe.**
Currently, you can only delete a row one at a time. Need ability to select and delete multiple rows at a time.

**Describe the solution you'd like**
Design file: [Link](https://www.figma.com/file/2ajhGblHmRYOiQSv0LHcyN/Multi-select?type=design&node-id=0-1&t=IBwEHcMDSCxl5MRO-0)

**Note**
- Implement only the table part of the design and not any other elements.
- When rows are selected the delete button options shows up on top of the page
- In case of any questions feel free to ask here or on [Discord](rowy.io/discord) to ensure you have good clarity on the design and implementation needed

**Comment by themohammadsa** [comment]
Hey @harinij! 
I am a new-comer to this repo, love the product as we had a genuine use-case for this at my workplace!
Also, I have setup the repo and really looking forward to contributing.


I like this issue, but have a doubt.

What does the 'needs-design' tag indicate here?
The design would be provided by rowy team or you are looking towards people contributing their ideas to it?

**Comment by harinij** [comment]
Hi @themohammadsa 👋 Welcome to the community. Great to have you hear and would like to learn more about your usecase at your workplace. Feel free to join the discussion on our [Discord](https://www.rowy.io/discord) 

The design for this will be mainly provided by the Rowy team, and the development contribution can be initiated after the design is finalized to ensure clear specs are in place. We have some rough designs at the moment but we will finalize it in our upcoming sprint and share them here.

**Comment by themohammadsa** [comment]
Sure, that's great to hear!

**Comment by newaritra** [comment]
/attempt #809

I'll take a stab at this as well :)

**Comment by themohammadsa** [comment]
Unfortunately, I had a look at the ticket requirements and the codebase - and I do not have the bandwidth currently to work on this now. 

So, for now, I am unassigning myself, and if anyone else wants to give it a shot - please go ahead! :)

**Comment by mnmt7** [comment]
Hey @bofeiw, can I work on this?

**Comment by ashutosh887** [comment]
@harinij @BeeBombshell  Let me attempt this one if not resolved yet!
I see it's unassigned
