### ISSUE TITLE
Copy button for Document Path

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#824]
**Is your feature request related to a problem? Please describe.**
Currently the "Document Path" linked in the side panel at the bottom, only has a URL link to open the document in another tab on Firebase console. It would be nice to have copy button as well right next to it to the copy the document path.
<img width="484" alt="Screen Shot 2022-09-20 at 12 36 06 pm" src="https://user-images.githubusercontent.com/307298/191154785-67678e6d-3120-46a1-bbf1-2df6a97e977a.png">

**Describe the solution you'd like**
Add a copy button right next to the Document Path
![image](https://user-images.githubusercontent.com/307298/191154476-67164ad2-9524-41e9-843b-5510b371ebb6.png)

**Comment by Rohitbels** [comment]
@harinij I would like to work on this issue.

**Comment by harinij** [comment]
This feature has been merged and released in the recent release.
