### ISSUE TITLE
Error: Rowy API fail /firebaseToken?projectId=preplaced-prod: 500

### ISSUE THREAD

**Issue by Shailesh248** [rowyio/rowy#833]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Rowy Run version**
If applicable, share the Rowy Run version from your project settings.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wzulfikar** [comment]
This issue has incomplete info (similar to #841) and possibly a duplicate of #843.

**Comment by notsidney** [comment]
Thanks, this issue has been fixed.
