### ISSUE TITLE
Error: Rowy API fail /firebaseToken?projectId=fire-demo-r4o99f: 500

### ISSUE THREAD

**Issue by EgorMaksimenko** [rowyio/rowy#841]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Rowy Run version**
If applicable, share the Rowy Run version from your project settings.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wzulfikar** [comment]
This seems like an issue with incomplete info and possibly a duplicate of #841.

**Comment by notsidney** [comment]
Thanks, this issue has been fixed.
