### ISSUE TITLE
Cannot delete a Rowy project if the Firebase project no longer exists

### ISSUE THREAD

**Issue by alta-atc** [rowyio/rowy#843]
**Describe the bug**
Firebase project has been deleted without first deleting the Rowy project, with Rowy now referencing an invalid firebase token. 

When clicking the Rowy project I get an error (attached) 
"Rowy API fail /firebaseToken?projectId=alta-labs-ygnnjp: 500"

Unable to remove the Project from Rowy 

**To Reproduce**
1. Create a Rowy project
2. Delete the firebase project
3. Try and access the project in Rowy using the navigation

**Expected behavior**
Continue to project but show that it has been unlinked from firebase. Or, allow me to delete the project.
![Uploading screencapture-rowy-app-p-alta-labs-ygnnjp-2022-09-26-10_11_27.png…]()

**Screenshots**
Attached

**Rowy Run version**
3.0

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version 106

**Comment by sasai** [comment]
Same problem. I removed Rowy related documents and roles on Firebase without deleting the project in Rowy.
I hope to try Rowy again, but I never create new project for the same firebase project because 
"This project has already been connected to Rowy. Please select a different one."

**Comment by notsidney** [comment]
Thanks for bringing this to our attention. We’re working on allowing you to delete projects from workspace settings.

**Comment by alta-atc** [comment]
I was able to workaround this by restoring the project from the GCP deletion queue, waiting a few hours and then accessing via rowy and removing, before deleting the project in GCP again.

**Comment by harinij** [comment]
You can now delete projects from workspace settings. 
<img width="641" alt="Screen Shot 2022-11-09 at 6 03 49 pm" src="https://user-images.githubusercontent.com/307298/200982598-fc569704-11fd-4c99-bba6-2781e4c7b979.png">

**Comment by alta-atc** [comment]
Y'all are the best. Love this project.
