### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by charliefairbairn** [rowyio/rowy#846]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Rowy Run version**
If applicable, share the Rowy Run version from your project settings.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by notsidney** [comment]
Hello, this looks like a UI bug. Please complete the “To Reproduce” section so we can investigate this.

**Comment by harinij** [comment]
Linked to duplicate issue where the bug fix will be tracked https://github.com/rowyio/rowy/issues/962
