### ISSUE TITLE
"Something went wrong - t.roles is not iterable"

### ISSUE THREAD

**Issue by notsidney** [rowyio/rowy#858]
### Discussed in https://github.com/rowyio/rowy/discussions/857

<div type='discussions-op-text'>

<sup>Originally posted by **alta-atc** October  7, 2022</sup>
I started encountering this issue immediately after enabling auditing on a subcollection. No tables in this project will load.

I experimented by changing the audit flag under _rowy_ / settings back to false, and this did not fix the issue. 

![Screenshot 2022-10-06 11 24 23 AM](https://user-images.githubusercontent.com/102269444/194368269-3354d9f8-52e7-489b-99af-7fdf52e415d5.png)
</div>

**Comment by harinij** [comment]
This issue is resolved in recent releases. Closing this out.
