### ISSUE TITLE
Error: Cannot set property id of <vp>

### ISSUE THREAD

**Issue by Modocosm** [rowyio/rowy#859]
Its crashing constantly when adding any row anywhere.
Updated chrome, firestore all setup.

**Comment by Modocosm** [comment]
![image](https://user-images.githubusercontent.com/106853815/194532071-af3b0fe3-6b8b-4426-b50b-0deb38a3dd8a.png)

**Comment by notsidney** [comment]
Hello @Modocosm, we need more info to investigate this issue.

1. Does this happen on all tables?
2. In the table that this occurs, does it have a ref field?
3. Is there already data in the table?
4. Do you have the side drawer open?
5. If you click the dropdown next to “Add row”, which option is selected?

**Comment by harinij** [comment]
Closing out the old issue. Most recent releases have bug fixes that potentially address this issue. If this issue occurs again, please open a new issue with the info on reproducing the bug as that would be helpful to investigate it further.
