### ISSUE TITLE
GeoPoint with Derivative

### ISSUE THREAD

**Issue by Prayer-RecycleSmart** [rowyio/rowy#885]
**Describe the bug**
Can get the function to return a GeoPoint

**To Reproduce**
```
const derivative:Derivative = async ({row,ref,db,storage,auth})=>{
    const { GeoPoint } = require('firebase/firestore');
    const test = new GeoPoint(-90,180);
    return test;
  }
```
**Expected behavior**
Should add a geopoint in Firestone/rowy

**Desktop (please complete the following information):**
 - MacOs 12.6
 - Safari

**Comment by shamsmosowi** [comment]
hi @Prayer-RecycleSmart 
Derivatives use firebase admin sdk
so it you need you use the `firebase-admin` npm instead of `firebase`

here's the working derivative
```
const derivative:Derivative = async ({row,ref,db,storage,auth})=>{
    const { GeoPoint } = require('firebase-admin/firestore');
    const test = new GeoPoint(-90,180);
    return test;
  }
```

**Comment by Prayer-RecycleSmart** [comment]
Thanks @shamsmosowi - love this product!
