### ISSUE TITLE
Automatically update columns when new data is added via Firestore SDK

### ISSUE THREAD

**Issue by paraschopra** [rowyio/rowy#899]
If I'm adding data directly to a collection via code here https://firebase.google.com/docs/firestore/quickstart#python

`doc_ref = db.collection(u'users').document(u'alovelace')
doc_ref.set({
    u'first': u'Ada',
    u'last': u'Lovelace',
    u'born': 1815
})[snippets.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/1bcabf0fddeb11e5870124f067f5bbc8ceedcd4c/firestore/cloud-client/snippets.py#L40-L45)`

The rowy interface should update with these columns, but it doesn't.

**Comment by paraschopra** [comment]
I guess you're storing schema in a separate collection and it doesn't get automatically refreshed.

**Comment by notsidney** [comment]
Hello, Firestore is by design a schemaless database. So if you add a new field, there is no table-level schema that gets updated automatically. Rowy only stores a list of columns, in a separate location in your Firestore database, that you manually add when creating tables.
