### ISSUE TITLE
Ability to change the font size of any Given column or cell.

### ISSUE THREAD

**Issue by Rohitbels** [rowyio/rowy#914]
**Is your feature request related to a problem? Please describe.**
Ability to change the font size of any Given column or cell.

**Describe the solution you'd like**
- Column config can have the ability to increase font size.

**Comment by mnmt7** [comment]
@harinij, I would like to work on this issue.

**Comment by harinij** [comment]
Thanks @mnmt7, We will put together quick designs for this together before you can get started on this so that the solution is clear. In the meantime, if you would like you can take a look at [this one](https://github.com/rowyio/rowy/issues/1244).

**Comment by harinij** [comment]
@mnmt7 We have decided to close this issue as doesn't work with the current design system and we might explore more styling themes in the future but out of scope for now. So closing this issue out. Instead, if you would like I have assigned I have tagged you on another issue if you want to take a look https://github.com/rowyio/rowy/issues/1247
