### ISSUE TITLE
Import/Export to include subtable config

### ISSUE THREAD

**Issue by harinij** [rowyio/rowy#934]
### Discussed in https://github.com/rowyio/rowy/discussions/860

<div type='discussions-op-text'>

<sup>Originally posted by **st-trade** October 11, 2022</sup>
I'd like to ask for table structure replication for subcollections/subtables.

Currently, each subtable in a record has to be initialized manually, since it's impossible to import table structure from other places. But it would be great if this schema was synced automatically.  Say, the same table structure for all subtables in a particular table.
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/94030557/195175750-d4f964f7-adb8-4000-b033-6e16549404c4.png">

</div>

**Comment by ganeshmani** [comment]
@harinij I would like to work on this.

**Comment by harinij** [comment]
This issue is now resolved as part of this PR: https://github.com/rowyio/rowy/pull/1066
