### ISSUE TITLE
The page freeze

### ISSUE THREAD

**Issue by Gweti** [rowyio/rowy#935]
Hello,
I'm really new on GitHub and it's the first time I'm posting, I hope I will be enough clear ;-)
**Describe the bug**
I have a table with 3 columns:
![Table](https://user-images.githubusercontent.com/117895389/201029836-9d1e7328-689c-45f2-b878-a6a8e01a7af2.png)
The first column is a JSon coming from another table (collection not subcollection)
When I try to edit a row I can open the window at right side of the screen to edit it but when I try to edit it freeze completely the page and I cannot do anything.
I have to reload the page to be able to edit or to make actions in the page.
I'm on Imac.
Thanks for help.
BR
G

**Comment by Gweti** [comment]
Found solution:
Pop-up that shows document details is not responding. Page becomes unresponsive and remains until hard refresh. Browser eventually kills the tab. #782

**Comment by notsidney** [comment]
Hi @Gweti, it looks like you’re storing a Firestore reference in the Card Reference **JSON** column. Please use a **Reference** column instead. This allows you to edit the document reference if you wish, as editing via the JSON column would no longer store it as a Firestore reference.
