### ISSUE TITLE
Enable filters that aren't case sensitive

### ISSUE THREAD

**Issue by dev-gardenr** [rowyio/rowy#947]
**Is your feature request related to a problem? Please describe.**
When filtering a column with a value, the filter takes lower or upper case into consideration, this is a problem since data can be in either.

**Describe the solution you'd like**
A dream would be for the filter to include values that matches both uppercase and lowercase text

**Describe alternatives you've considered**
Scripting my entire database to only allow lowercase, but case needs to be considered for application functions

**Additional context**

**Comment by harinij** [comment]
@dev-gardenr we have a full-text feature now that allows for flexible search of tables. You can find details about it here: [https://docs.rowy.io/full-text-search](https://docs.rowy.io/full-text-search)
