### ISSUE TITLE
New column type for Array - To be displayed as with subtable view

### ISSUE THREAD

**Issue by shamsmosowi** [rowyio/rowy#959]
Add  a new column type: **ArrayTable**

This is a repeated ask from users of Rowy to support array fields of Firestore, for example [here](https://github.com/rowyio/rowy/discussions/956)

**Task:**
- Create a new column type called Array: Documentation for adding a new column is available [here](https://docs.rowy.io/contributing/add-a-field-type).
- This Array field on the Rowy Table UI should open similarly to how [subtable](https://demo.rowy.io/table/allFieldTypes/subTable/allFieldTypes%2F08np1ItulUrTjNTmfLNU/subtable?parentLabel=This%20is%20a%20test%20for%20action%20%20dhad%20dadlfkj) column type shows up.
- However on the Firestore side, the data should be stored as an array as shown below and not a subcollection (subtable field is stored as a subcollection).
<img width="615" alt="Screen Shot 2022-12-30 at 1 02 27 am" src="https://user-images.githubusercontent.com/307298/209964191-dfe24a3f-b2fe-441c-b930-302638f362f8.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/53828745/202520232-675334a2-8d99-4852-8a87-d9d007abde36.png">
</div>

**Comment by S-P-Ks** [comment]
I can take this task.

**Comment by harinij** [comment]
Hi @S-P-Ks I have assigned the task to you. Please join us on [discord](https://www.rowy.io/discord) if you like any additional information or want to discuss technical details under the #contribution channel.

**Comment by ashutosh887** [comment]
HI @harinij 
Is this Task resolved?

**Comment by ashutosh887** [comment]
Thanks for assigning me!
Can you tell me how to get started with Project @shamsmosowi !

**Comment by harinij** [comment]
@ashutosh887 since you are already assigned #519, I am going to unassign this task from you and reassign it to someone else as per our contribution guidelines

**Comment by jyash97** [comment]
Hey 👋 

I am working into this issue, and have setup the project locally and looked into how the to add the column. 

But not sure how do we want to render the UI, if you can give more context on the UI of editing and displaying the cell value. Do we want the array to be typed ? Like shown in the screenshot ?

**Comment by shamsmosowi** [comment]
hi @jyash97, 
To give you more context, we already have column type called [subtable](https://docs.rowy.io/field-types/sub-table), which renders a table for specified subcollection. The idea here is to have the same experience but for an array of objects in same document rather than in a subcollection.
highly recommend trying out the subtable column type first, it should give you a good idea

**Comment by jyash97** [comment]
So we want a bottom drawer ? With a button to add array item and the item can be string, number or even a JSON  ?

**Comment by shamsmosowi** [comment]
Yes, it'll be a bottom drawer like the subtable, and you can add JSON objects to the array instead of documents in a subtable

**Comment by jyash97** [comment]
@shamsmosowi  

I was looking at JSON field type as well, it also provides a option to add array, couldn't that be done through that ?

**Comment by shamsmosowi** [comment]
Yes, currently that's the only way of modifying arrays on rowy. However, it's not as intuitive as the table experience
